### PR TITLE
20176-Error-in-ByteArray-booleanAt

### PR DESCRIPTION
**Pull request by estebanlm**
fix booleanAt: 

fixes issue #20176

### CODE REVIEW

**Comment by estebanlm** [comment]
issue was completely wrong

**Comment by dionisiydk** [comment]
Such things are really required tests. Can you add them?

**Comment by estebanlm** [comment]
not really. I just merged an external package (FFI-Kernel).

**Comment by tesonep** [comment]
I rebased this PR so it only has the real changes. After @pavel-krivanek reexported the symbol literals

**Comment by estebanlm** [comment]
yeah, that looks better :)

**Pull request merged**
