### PR TITLE
20970 remove pharo 6 platform class from pharo 7

### PR DESCRIPTION
**Pull request by theseion**
Added Fuel platform class for Pharo 7.
Removed Fuel platform class for Pharo 6.

Replaces https://github.com/pharo-project/pharo/pull/674.

https://pharo.fogbugz.com/f/cases/20970/Remove-Pharo-6-platform-class-from-Pharo-7

https://github.com/theseion/Fuel/issues/227

### CODE REVIEW

**Comment by estebanlm** [comment]
as @jecisc points... this will need an update in the baseline :(

**Comment by theseion** [comment]
I don't understand. Which baseline are you talking about?

**Comment by jecisc** [comment]
Since Pharo 7 is bootstraped, the package loading is done via Baselines. (For example: BaselineOfIDE)
So, When packages are changed, the Baseline needs to be updated.

**Comment by estebanlm** [comment]
in this case, this is `BaselineOfMorphic` (don't ask why)

**Comment by theseion** [comment]
*facepalm*

**Comment by pavel-krivanek** [comment]
I opened an issue: https://pharo.fogbugz.com/f/cases/20974/make-standalone-baseline-for-Fuel

**Comment by pavel-krivanek** [comment]
and for fixing of the baselines: https://pharo.fogbugz.com/f/cases/20975/Fix-baselines-after-Fuel-update-case-20970

**Pull request merged**
