### PR TITLE
20239 Separate and rename Bytecode Encoders

### PR DESCRIPTION
**Pull request by clementbera**
https://pharo.fogbugz.com/f/cases/20239/Separate-and-rename-Bytecode-Encoders

### CODE REVIEW

**Comment by estebanlm** [comment]
it looks fine for me but I think is @MarcusDenker who can evaluate it better :P

**Comment by jecisc** [comment]
Maybe tests can be relaunch?

**Comment by MarcusDenker** [comment]
I restarted the tests

**Comment by jecisc** [comment]
Apparently there is merge conflicts to resolve

**Pull request closed without merging**
