### PR TITLE
20316-Renraku-10

### PR DESCRIPTION
**Pull request by Uko**
Merged the latest improvements from Renraku.
The description of the new features is available here: https://github.com/Uko/Renraku/releases/tag/v1.0.0

### CODE REVIEW

**Comment by Uko** [comment]
What's up with `FuelTests-Test.xml.[failed-to-read]`? I cannot reproduce any issues with those tests

**Comment by jecisc** [comment]
Uko, I think this is a random failure because I got the same kind of errors on some PR and after Pavel relaunched the checks it was green.

**Comment by Uko** [comment]
@jecisc how I can relaunch the checks?

**Comment by jecisc** [comment]
@Uko I assume that for now only people with rights on the "pharo" inria's CI can do it. But maybe I'm wrong. @pavel-krivanek or @guillep might give further details.

**Comment by pavel-krivanek** [comment]
trying again

**Comment by Uko** [comment]
So what do we do with this one? Because I cannot understand the test failures, and I cannot recreate them in my image

**Pull request merged**
