### PR TITLE
20632-Rename-PluggableSortFunction-to-CollatorBlockFunction

### PR DESCRIPTION
**Pull request by dionisiydk**
PluggableSortFunction is renamed to CollatorBlockFunction

### CODE REVIEW

**Comment by dionisiydk** [comment]
Just tiny change for previous SortFunction refactoring.
https://pharo.fogbugz.com/f/cases/20632/Rename-PluggableSortFunction-to-CollatorBlockFunction

**Comment by nicolas-cellier-aka-nice** [comment]
Why CollatorBlockFunction and not just CollatorFunction?

**Comment by dionisiydk** [comment]
All sort functions are collators. 
This one uses block as collation implementation. So I named it with block word.

**Comment by nicolas-cellier-aka-nice** [comment]
But `SortByPropertyFunction` also is implemented with a block (a valuable) and is not called Block. Isn't it an implementation detail?
Or do you plan to have other kind of CollatorFunction and want to distinguish?

**Comment by dionisiydk** [comment]
SortByPropertyFunction is based on any valuable object, not only block. it can be a symbol. They not implement collation logic. They only extract property from sorted objects. 
Actual collation is responsibility of function itself where it compares extracted properties.

**Comment by nicolas-cellier-aka-nice** [comment]
But passing the symbol #< would also work as a collation function, because it understands value:value:, wouldn't it?
I ask about Block and you constantly reply Collation...

**Comment by dionisiydk** [comment]
In that case block should perform three way comparison returning 1, 0 or -1. So #< selector is not working here. Of course you can use another selector. But generally users should not do this. If you will think about such two args selector then you should implement your domain SortFunction instead. And that was one of the goals for this refactoring: to be able implement reusable custom functions.

Imaging SortMethodFunction which take care about binary selector ordering (which is always on top of list). It will be quite ugly to put this logic inside block or some application method. And it will be not reusable.

Another goal of refactoring is to use sort functions in caches. Function based on block will lead to memory leak. But custom functions can be used safely. And SortByPropertyFunction is safe when it is created on selector. In previous version any sort function was based on block.

**Comment by nicolas-cellier-aka-nice** [comment]
Yes, selector does not really matter, spaceship operator `#<=>` would do, or `#threeWayCompareTo:` as it was renamed in Pharo if you prefer
(I wonder why??? `<=>` is SO elegant!!! I see it as lack of respect of original author http://objology.blogspot.fr/2010/11/tag-sortfunctions-redux.html).

I don't know if you realize it, but above selector is the default Collator Function (as for example used in `SortByPropertyFunction`). It's just that it is hardcoded rather than reified.

Imagine I want to sort by some property first, then by another. But those properties are neither String nor Magnitude, or they are, but I want a different collation policy, because in French `$é` must not be sorted too far from `$e`.

It's obvious that we'll need a SortByPropertyAndCollationFunction if we want something easily composable as we have now. The name sounds well too long, so maybe every SortByPropertyFunction should have its collationFunction reified...

When I see `Block`, I think you're telling me how (implemented with a Block) rather than what it is (a CollatorFunction).
But CollatorBlockFunction is nothing but an intermediate which transforms the `#value:value:` message into a more revealing `#threeWayCompare:with:`.
Other collating functions will be implemented in own classes, so the name can stay, I agree now.

But we will have to refactor the library so that we can compose collation applied on properties like I mentioned above.

And now there's another name that upset me: `#threeWayCompare:with:` is a a more ugly name of `#collate:with:`, but intended to be privately used in `SortFunction` before changing direction... 
That's unfortunate, for me a Collator collates, so I'd expect the second selector when I'll implement my own Collator.

Thanks for patiently answering to me, you have materials for building a great library, and it's better to carefully choose the words early than late...

**Pull request merged**
