### PR TITLE
20288-Fix-failing-tests-in-pharo-70

### PR DESCRIPTION
**Pull request by guillep**
Fix 7 failing tests in Pharo CI

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
testAsRepositorySpecFor has bad indent (one more tab).

**Comment by pavel-krivanek** [comment]
it is optional, the rest is ready to be merged

**Comment by pavel-krivanek** [comment]
Related issue that should be closed: https://pharo.fogbugz.com/f/cases/18566/FileHandle-does-not-truncate-file

**Comment by guillep** [comment]
I fixed the identation. I kept the block indented to show it's a block. In any case, the test implementation smells:
 - we could use a helper method instead of a block
 - we could split that test in 4 tests (one per usage of the block)

But refactoring of that test is not part of this issue.

**Comment by guillep** [comment]
Actually, we should not close https://pharo.fogbugz.com/f/cases/18566/FileHandle-does-not-truncate-file

Reading the comments in that issue made me realize that this patch just fixes the test but may have a buggy behaviour. A more complete fix (that should come with tests) should include the code proposed by @sbragagnolo using:

```smalltalk
truncateTo: anInteger
    | lastPosition |
    self assureOpen.
    lastPosition := Primitives getPosition: id.
    lastPosition := lastPosition min: anInteger.
    Primitives setPosition: id to: 0.
    Primitives truncate: id to: anInteger.
    Primitives setPosition: id to: lastPosition.
    self reopen
```

**Pull request merged**
