### PR TITLE
21124 ffi should work without the sources

### PR DESCRIPTION
**Pull request by VincentBlondeau**
Let's try the integration in the image!

I added a new pragma, ffiCallMethod, on the methods of the API where the argument names have to be recorded

### CODE REVIEW

**Comment by VincentBlondeau** [comment]
https://pharo.fogbugz.com/f/cases/21124/FFI-should-work-without-the-sources

**Comment by MarcusDenker** [comment]
It seems that tests related to FFI are failing

**Comment by tesonep** [comment]
Why they are not added to all the methods with FFI during compilation?

**Comment by dionisiydk** [comment]
Good work Vincent.
I put questions into fog bugs

**Comment by dionisiydk** [comment]
So I create new pull request #749  with proposed changes. This one can be closed

**Pull request closed without merging**
