### PR TITLE
20641-Disable-FreeType-plugin-by-default

### PR DESCRIPTION
**Pull request by pavel-krivanek**
disable FreeType by default

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
https://pharo.fogbugz.com/f/cases/20641/DIsable-FreeType-plugin-by-default

**Comment by pavel-krivanek** [comment]
We should create StrikeFonts for the default Pharo TTF fonts

**Comment by estebanlm** [comment]
can't we wait for Ronie's output before going for this? 
I feel is a huge step backwards if we do it :( 
if we still do this, can't we fist include a good monospaced bitmap font? I don't know, like this one: https://www.dafont.com/bitstream-vera-mono.font

**Comment by pavel-krivanek** [comment]
I'm trying to convert Source Code Pro fonts to bitmap ones. Maybe we do not need to disable it by default but we should have the same look of default Pharo with FreeType and without them. We should clean the way how fonts are imported into the image too. Now we have the date for fonts but we are using a Fuel file anyway.

**Comment by pavel-krivanek** [comment]
Decreases quality of the default fonts - not approved by Esteban. In meantime we fixed in separate issues the switching to the proper bitmap fonts when FreeType fonts are disabled and the display size. In separate issue we should make a better logic for selection of the fonts when FreeType is not available. 

Closing this PR and issue

**Pull request closed without merging**
