### PR TITLE
20399 Properly categorize hash methods in comparing protocol

### PR DESCRIPTION
**Pull request by astares**
Properly categorize hash methods in comparing aand add a release test that checks this

https://pharo.fogbugz.com/f/cases/20399/All-hash-methods-should-be-properly-categorized

### CODE REVIEW

**Comment by Ducasse** [comment]
Hi torsten 
I will integrate this but after we should check because some recategorisation tests are not working. We want to have the bar green. 

Stef

**Comment by astares** [comment]
Can you tell me which ones are failing now?

**Comment by Ducasse** [comment]
https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/development/108/#showFailuresLink

ReleaseTests.Categorization.ProperMethodCategorizationTest.testHashMethodNeedsToBeInComparingProtocol
ReleaseTests.Categorization.ProperMethodCategorizationTest.testHashMethodNeedsToBeInComparingProtocol
ReleaseTests.Categorization.ProperMethodCategorizationTest.testHashMethodNeedsToBeInComparingProtocol
ReleaseTests.Categorization.ProperMethodCategorizationTest.testHashMethodNeedsToBeInComparingProtocol
ReleaseTests.Categorization.ProperMethodCategorizationTest.testHashMethodNeedsToBeInComparingProtocol
ReleaseTests.Categorization.ProperMethodCategorizationTest.testHashMethodNeedsToBeInComparingProtocol
ReleaseTests.Categorization.ProperMethodCategorizationTest.testHashMethodNeedsToBeInComparingProtocol
ReleaseTests.Categorization.ProperMethodCategorizationTest.testHashMethodNeedsToBeInComparingProtocol

**Comment by astares** [comment]
This is because IceSemanticVersion>>#hash is not in comparing. Will send another PR

**Comment by astares** [comment]
I tried to fix https://pharo.fogbugz.com/f/cases/20401 (which would be trivial) to get the build green. But IceSemanticVersion is an Iceberg class and when I modify it Iceberg does not show me any changes on the "pharo" repo. I guess this is because Iceberg is not included (which is confusing)
and managed externally in an own project. 

Asked Esteban on Discord on how to proceed - I guess it need to fixed in Iceberg repo and then moved over ...

**Comment by astares** [comment]
New PR to Iceberg Repository initiated:

https://github.com/pharo-vcs/iceberg/pull/458

Requires integration there and integration of updated Iceberg version into Pharo 7. Details in https://pharo.fogbugz.com/f/cases/20401

**Pull request merged**
