### PR TITLE
20688-move-Monticello-Browser-to-the-Tools-submenu-in-the-World-menu

### PR DESCRIPTION
**Pull request by pavel-krivanek**
https://pharo.fogbugz.com/f/cases/20688/move-Monticello-Browser-to-the-Tools-submenu-in-the-World-menu

Move Monticello Browser to the World menu under the Catalog Browser

### CODE REVIEW

**Comment by jecisc** [comment]
Hum… I am not sure it is a wise choice for Pharo 7. 

Monticello is still used a lot and it will be used by a lot of user in Pharo 7 because Iceberg is not stable enough for most companies. Also companies takes time to change their process. To get only an unstable cvs tool in the most used tool is maybe not a good choice.

**Comment by estebanlm** [comment]
iceberg will not be unstable when releasing.

**Comment by astares** [comment]
I would group both into an own submenu "Version Control" instead of hiding  Monticello in the Tools menu.

For some development (where git is not available/not an option) Monticello is still valid.

**Comment by jecisc** [comment]
I like the proposition of Astares.

**Comment by pavel-krivanek** [comment]
then it can be both directly in the Tools submenu :-)

**Comment by jecisc** [comment]
Grouping them in a "VCS" sub menu can help the users I think. 

There was some discussions some time ago in the ML to point that we have a lot of tools with cool but non explicit names. This is the case with "Iceberg" and "Monticello", but having them under "VCS" help the new users. 

Or if they are under Tools, then it would maybe be better to rename the menu entries to something like "Git" and "Monticello VCS".

**Comment by astares** [comment]
Yes - if you do not follow pharo directly you do not know that Iceberg is git access.

Also under SystemBrowser in the past we had the old browser, now "Nautilus" and later "Calypse"
but System Browser is a meaningful name.

**Comment by pavel-krivanek** [comment]
closing

**Pull request closed without merging**
