### PR TITLE
20381 Categorized methods in vs unload unit and vm window driver 

### PR DESCRIPTION
**Pull request by astares**
https://pharo.fogbugz.com/f/cases/20381/Uncategorized-methods-in-VSUnloadUnit-and-VMWindowDriver

### CODE REVIEW

**Comment by jecisc** [comment]
Target branch needs to be development

**Comment by astares** [comment]
Invalid - will create a new one

**Comment by estebanlm** [comment]
you know that you can just edit the target ? (on github, you go to “edit” on PR and you will be able to change the target)

Esteban

**Comment by astares** [comment]
Yes I know and tried. But GitHub showed a red error afterwards when I switch to #development branch.

I created a new PR already. https://github.com/pharo-project/pharo/pull/247

**Pull request closed without merging**
