### PR TITLE
20905-upToAll-for-ZnCharacterReadStream

### PR DESCRIPTION
**Pull request by bpieber**
initial implementation of ZnCharacterReadStream>>#upToAll:

### CODE REVIEW

**Comment by Rydier** [comment]
It's useful for parsing telegrams line by line stop or, more likely, other formats with a similar structure stop

**Comment by bpieber** [comment]
Can someone please help me with the failing CI checks. I have no idea how you debug failures like this? Is there a way to run the checker locally?

**Comment by MarcusDenker** [comment]
I have restarted the CI

**Comment by tesonep** [comment]
I have rebased the commit with the latest development. Because the error was really strange, it was trying to load a package that is no more in the repo..

**Pull request merged**
