### PR TITLE
17299 sleep longer than a second in the delay scheduler

### PR DESCRIPTION
**Pull request by zecke**

### CODE REVIEW

**Comment by guillep** [comment]
@bencoman could you review this issue?

**Comment by bencoman** [comment]
I'll take a look.

**Comment by Ducasse** [comment]
Hi ben

Is it ok?

Stef

**Comment by bencoman** [comment]
Sorry for the big delay.  Interspersed with 12 hour mine site work days and quality family time in my off-swing, I finally managed to sort out my Pharo7/Iceberg/PR-review process. My work flow was slightly wrong as I just described on discord #iceberg channel.

Okay, so I like the change, but not where its made.  Rather than modify DelayMicrosecondScheduler, this feature should be done in a new subclass, so that end-users can switch such features in/out if they need to isolate features to troubleshoot issues.  This also allows a staged approach to adoption, separate from code integration.

What would be a good name for the subclass... "DelayTicklessScheduler" ?

**Comment by zecke** [comment]
Sure. We can do it. Would you only want it for the Microsecond or Millisecond one as well? Can we remove the Millisecond and other schedulers?

**Comment by bencoman** [comment]
Ignore the Millisecond scheduler.  It was kept as a safeguard being identical to the code before I re-factored the classVar structure to instance variables and the change to microsecond scheduling.  It was never used and I plan to remove it along with some clean up refactoring I have in progress now I'm tuned into Pharo7 dev process.

**Comment by zecke** [comment]
@bencoman like this? I will write a better commit message in a bit but wanted to get it out. What do you think of the changes to the testcases?

**Comment by bencoman** [comment]
I like what you did adding #delaySchedulerClass.
For DelayTicklessSchedulerTest, maxTicks is no longer relevant. I think the test should be...
	duration := 10000 milliSeconds. 
	nowTick := 100 milliSeconds.
	expectedTick := nowTick + duration. "delays are full period, no artificial limits"
	...
	self assert: nextTick equals: expectedTick asMicroseconds.

**Comment by bencoman** [comment]
Activating this tickless scheduler via "Delay delaySchedulerClass: DelayTicklessScheduler" 
(or System > Settings > System > Delay Scheduler)
worked fine for me - but then again the UI loop has a 50ms interval so the VM is never set to zero.

Aside: The following tests are not of concern against integrating this issue, but just interesting as I guess the ultimate future goal is for something like this... 
The following crashed the VM with "scheduler could not find a runnable process"...
  processes := (Process allInstances select: [:p | p isTerminated not ]) 	
                                         sorted: [:p1 :p2 | p1 priority > p2 priority ].
  processes := processes allButFirst. "leave delay scheduler running"
  [	processes do: [:p| p suspend].  
	5 seconds wait.
	processes do: [:p| p resume].
  ] fork. 

and with...
    processes := processes allButFirst allButLast. "ignore delay scheduler and idle processes"
my image locked.

**Pull request merged**
