### PR TITLE
16969-Use-a-Rectangle-instead-of-a-Margin

### PR DESCRIPTION
**Pull request by Ducasse**
https://pharo.fogbugz.com/f/cases/16969/Use-a-Rectangle-instead-of-a-Margin

### CODE REVIEW

**Comment by jecisc** [comment]
This PR includes also #595

Maybe we should wait the integration of #595 before working on this one

**Comment by Ducasse** [comment]
oops I thought that I filtered it. 
Indeed I think that we are pretty slow to integrate comments.

**Comment by Ducasse** [comment]
I added on the bug entry https://pharo.fogbugz.com/f/cases/16969/Use-a-Rectangle-instead-of-a-Margin a fileout of the code so that we can redo the pull request and I do not lose my work. I do not know how to take a commit and recommit it while cherrypicking the changes.

**Comment by jecisc** [comment]
If we integrate #595 maybe there is no need to redo a PR.

**Comment by Ducasse** [comment]
Indeed ;) What is super strange is that this one included the other is green while the other is not :)

**Comment by pavel-krivanek** [comment]
broken because of a deleted fork.
redone here:https://github.com/pharo-project/pharo/pull/650/files

**Comment by MarcusDenker** [comment]
I close this one

**Pull request closed without merging**
