### PR TITLE
20384-Converted-rules-to-Renraku-architecture

### PR DESCRIPTION
**Pull request by myroslavarm**
updated rules and fixed tests for them

### CODE REVIEW

**Comment by guillep** [comment]
There was a problem while running the build.

`MCPackageLoader>>warnAboutDependencies`

Check

https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-253/1/console

**Comment by guillep** [comment]
@myroslavarm , @Uko we can check it afterwards if you want. This is a dependency problem.

**Comment by Uko** [comment]
I think I know what is happening. Originally Renraku depended on SmallLint. Now SmallLint tules were reimplemented and depend on Renraku. We have to see if we can just reverse the Renraku <-> SmallLint dependency or there are some cycles now

**Comment by Uko** [comment]
I suggest moving the transformed Rules into a new package called `GeneralRules` with tag `Migrated` because this way we will not get a dependency clash and still keep track of rules that have to be looked over and dispatched into more appropriate packages.

**Comment by estebanlm** [comment]
it must be redone

**Pull request closed without merging**
