### PR TITLE
20116-Add-is64bit-and-is32bit-methods-in-order-to-distinguish-between-those-two-cases

### PR DESCRIPTION
**Pull request by JurajKubelka**
Add is32bits and is64bits methods to VirtualMachine class. 

Discussed with Esteban Lorenzano on Dicord during the Pharo Sprint June 2, 2017.

https://pharo.fogbugz.com/f/cases/20116

### CODE REVIEW

**Comment by MarcusDenker** [comment]
would not is32bit be better than is32bits? the term is normally used singular (64bit processor, not 64bits processor)

**Comment by MarcusDenker** [comment]
https://en.wikipedia.org/wiki/64-bit_computing

**Comment by astares** [comment]
Yes - singular would be better than plural

**Comment by estebanlm** [comment]
really? I always thought it was in plural (in fact `FFIExternalStructuePlatformTests` has an implementation of `#is32bits` and `is64bits` that needs to be refactored, in that case :)

**Pull request merged**
