### PR TITLE
20045-No-one-uses-RBLintRule-longDescription-almost-no-one-implements

### PR DESCRIPTION
**Pull request by pavel-krivanek**
https://pharo.fogbugz.com/f/cases/20045/No-one-uses-RBLintRule-longDescription-almost-no-one-implements

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
Deprecated60 was removed from Pharo 7, we need to setup new package

**Comment by Uko** [comment]
looks good!

**Comment by estebanlm** [comment]
no, this do not work (a mystery why). Reverting.

**Comment by pavel-krivanek** [comment]
The bootstrap process started to load Deprecated70 package soon because of deprecated FileStream. So this extension of the Deprecated70 package breaks it. I will open an issue.

**Comment by pavel-krivanek** [comment]
So code in this PR is OK, Pharo packages need to be fixed...

**Comment by estebanlm** [comment]
ok, I'm reverting the issue, just let me know when is ready again :)

**Comment by apblack** [comment]
I think this can now be "unreverted".  But I don't know how to do that.  Esteban?

**Comment by estebanlm** [comment]
you have to submit a new PR :)

**Pull request merged**
