### PR TITLE
19105-Default-time-limit-for-tests-should-be-really-small

### PR DESCRIPTION
**Pull request by pavel-krivanek**

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
merging development into the PR branch had no conflict so I do not understand why it complained

**Comment by guillep** [comment]
Let's wait the tests don't break with this change. Otherwise we should adapt tests also to say an explicit timeout.

**Comment by guillep** [comment]
Looks ok

**Comment by dionisiydk** [comment]
Cool.
So 10 seconds is now default timeout. Good

2017-10-20 15:40 GMT+02:00 Guillermo <notifications@github.com>:

**Pull request merged**
