### PR TITLE
20942-Integrate-Epicea-826-in-Ph7

### PR DESCRIPTION
**Pull request by tinchodias**
Upgrade Epicea to 8.2.7 (but keep Cyril's contribution in this repository which is not copied upstream yet).

Changes:

- Fix case 20223.
- Fix EpLog and OmFileStore #entryReferences, the result must have the same order as #entries.
- Improve apply preview of class comments.
- Sync with changes in Pharo 7: remove override of ZnBufferedWriteStream>>#cr since it''s already present in latest version of Zinc.
- Improve some code comments.
- Fix refactoring apply (general case)
- Fix class rename refactoring

### CODE REVIEW

**Comment by tinchodias** [comment]
https://pharo.manuscript.com/f/cases/20942/Integrate-Epicea-8-2-7-in-Ph7

Note: I changed case's title after creating the branch. That's the reason of the mismatch between 8.2.6 and 8.2.7.

**Comment by tinchodias** [comment]
The error log seems unrelated to the change

**Comment by dionisiydk** [comment]
Hi Martin. 

> keep Cyril's contribution

Is it required some manual action?

**Comment by MarcusDenker** [comment]
I understand it that this pull requests keep the additional changes (they will be then adde do the upstream later, too)

**Comment by tinchodias** [comment]
@dionisiydk no manual action needed. 

It is change in a method that Cyril did in this repo but I still didn't merge into sthub/Epicea, but in my git commit I preserved his contribution.

**Pull request merged**
