### PR TITLE
20688 - 

### PR DESCRIPTION
**Pull request by badetitou**
move Monticello Browser to the Tools submenu in the World menu

### CODE REVIEW

**Comment by jecisc** [comment]
Hi,

Before integrating maybe it would be good to read the messages here: https://github.com/pharo-project/pharo/pull/478

**Comment by badetitou** [comment]
Oh yes .... But it doesn't appear on fogbugz... Rhaaa

**Comment by jecisc** [comment]
:)

**Comment by astares** [comment]
Dont know why Pavel closed #478 - I would follow my own proposal - but I'm biased then ;)

**Comment by pavel-krivanek** [comment]
We did a cleanup of PRs and there was no consensus on the integration of this one. The World menu needs better complex reorganization than these random changes (at least according to me and Denis) so I closed that.

**Pull request closed without merging**
