### PR TITLE
20285 add jenkins file into repository

### PR DESCRIPTION
**Pull request by guillep**
Building and testing using jenkins file

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
for the tests the ReleaseTests should be started on a fresh image without any other tests. We usually delete old ReleaseTests results after running all tests and run them again

**Comment by guillep** [comment]
How is that related to the PR?

Release tests are not failing, I don't see why we need to run Release tests differently...

https://ci.inria.fr/pharo-ci-jenkins2/job/Pharo-PullRequest-Pipeline/158/#showFailuresLink

**Comment by guillep** [comment]
This is built already using the jenkins file and we got 7 failing tests

https://ci.inria.fr/pharo-ci-jenkins2/job/test%20multibranch%20pipeline/job/PR-178/1/

**Comment by pavel-krivanek** [comment]
at the end of runTests.sh we call all tests

**Comment by guillep** [comment]
Yes but I don't see why that is a problem

**Pull request merged**
