### PR TITLE
20495-FullBlockClosure-not-working-in-Pharo-7

### PR DESCRIPTION
**Pull request by clementbera**
Added fixed calss index for fullBlock closure
This fix requires 2 pull requests, one in Espell and one here. The Espell pull request has to be integrated first.
https://pharo.fogbugz.com/f/cases/20495/

### CODE REVIEW

**Comment by clementbera** [comment]
I added two methods which are not called. I don't understand how the PR can be denied.

**Comment by pavel-krivanek** [comment]
it is not needed to deny it because we are not re-checking every PR for each build. The validation will be restarted as soon as you make a change into your branch (with bootstrap image URL update)

**Comment by tesonep** [comment]
@clementbera It failed because the change requires a new release of the Espell process. Once there is a new released version we can point the bootstrap process to it, and run it again.

**Comment by tesonep** [comment]
@clementbera I have updated the process to use the new version of Espell, let's see if it works.

**Comment by tesonep** [comment]
@clementbera The whole process run fine. [Here](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/view/change-requests/job/PR-337/lastSuccessfulBuild/artifact/) you can find the different images to see if the classes are created correctly.

**Comment by estebanlm** [comment]
so? go or no-go?

**Comment by clementbera** [comment]
It worked. 'FullBlockClosure basicIdentityHash = 38'. Please integrate.

**Pull request merged**
