### PR TITLE
20755-Tests-that-make-no-assertions-should-fail

### PR DESCRIPTION
**Pull request by apblack**
Fixes some of the failing tests in the collections hierarchy. There is more to do, but this is at least a start!  

Please do not reject this pull request because there are now several hundred failing tests!   These tests have been failing for years; all that this PR does is *reveal* that these tests are failing (to do anything useful).

### CODE REVIEW

**Comment by jecisc** [comment]
If we add this behaviour we should remove this lint: RBShouldntRaiseErrorRule.

**Comment by MarcusDenker** [comment]
I would prefer to have the CI setup working once before adding lots of failing tests... We are really fighting to get it green and are not succeeding.

**Comment by astares** [comment]
1. In comment 1 you wrote: "Fixes some of the failing tests in the collections hierarchy."

   Where do we have failing test in the collection hierarchy?  

   Could you elaborate a little bit:
     -  more what you mean. In recent images the collection tests are green.
     -  what you are additionally trying to solve beside introducing "failing tests for tests 
        without assertions" (as the subject states)? 

2. In FogBugz you wrote: "When a test runs without error, but makes no assertions, it should fail."
    
   Why do you think so? A test method should run without failing and be green, thats all. 

   There is no explicit need to use an assertion or one of the convinience methods like 
   #assert: or deny:. An assertion is optional and could but must not be used to check 
   after some testing code is run.

   So even an empty test could be green

```Smalltalk
        testNothing
              "Do nothing"
```
   or even a method that just tests a call without checking:

```Smalltalk
        testFooIsCallableWithoutHazzle
              "Test that foo is called without crashing"
              SomeUnstableClass foo
```
    If the #foo call crashes the test will be red anyway without any assertion.

3. As one can also work without using methods like #assert: a test written like this:

```Smalltalk
    testSomething
            someIVar = 2 ifTrue: [ self fail ]
```
  might be perfectly green without your changes. My understanding from manual code review 
  here in github (without checking directly in Pharo) would run such tests red afterwards.

  So this change would introduce trouble.

2. I see no value in changing this behavior of the pretty standard SUnit lib by introducing another
    layer of complexity.
   
    There are better places to have incompatibilities with other systems. SUnit is pretty 
    standard and necessary to port things over from/to other Smalltalks. For sure we can also 
    change or fix SUnit - but only if we have a clear benefit and I still fail to see which benefit
    we have with these changes ...

4. If you need exactly this (very special) behavior for your project you could easily 
    introduce an own custom subclass of TestCase like "TestCaseEnsuringAsserts"
    and by overwriting SUnit methods #assert: get the behavior you want

5. I also agree with Marcus - there is no need to introduce failing tests now. 

So from the informations/changes given so far and from the points given in 1-5 
I currently would not to include this PR.

**Comment by astares** [comment]
by the way: this is also green in Java

```Java
public class Simple extends TestCase {
    
    @Test
    public void testFoo() {
        
    }
}
```

**Comment by estebanlm** [comment]
no, I disagree with this change. 
@astares has done a good job explaining why and this is my adds:

tests that do not make assertions are often there to just prove that something does not raises an error. 

years ago we did the oposite change and we remove all assertions of the form #should:raise: and #shouldnt:raise:, and I bet those failing tests were the tests like that. 

metacello for example has several tests like that: they are there just to confirm it does not raises errors. 

So. I'm sorry, but I'm rejecting this change (here and at fogbugz).

**Comment by apblack** [comment]
> tests that do not make assertions are often there to just prove that something does not raises an error.

Yes, some of them are.  But if you take a look, you will find that many of them are not.  Indeed, most of them are buggy tests.  For example, the tests of collections that I reported in 2013 (Issue #7478) are broken because the person who wrote them did not understand how to use a stream.  
They remain broken because they produce a misleading green when they run.  Many of the tests that were corrected in this PR are broken because stuff is written to a stream, and then the tester forgets to reset the stream before examining it.  In both cases, there are assertions in a `#do:` that are never executed, because the `#do:` is sent to an empty object. 

Yes, there are, as you say, some tests that are there "to just prove that something does not raises an error".  That's fine; flag them at the top with `self smokeTest` and everyone will be able to see that's what they are there for.  You could even add that flag automatically to every test that _statically_ does not contain any assertions.  The ones that are still failing are probably buggy, and deserve to be looked at by hand.

If you look at some of these smoke tests, though, you will see that there is often another test that does the same thing, but then makes one or more assertions.  In this case, the smoke test does nothing other than slow down the build.

Whether you accept or reject this depends on whether or not you are interested in finding bugs.   If you would rather have green tests that assure you of nothing, then reject it.  That may make you feel good ("look at all my green tests"), but will not improve the quality of the software.  If you are interested in revealing bugs, then I believe you should keep it.

As the commit message says, you can also return the default behaviour to the current one by changing the definition of TestCase class >> #assertionlessTestsShouldFail so that it returns false.
SUnit will then tally and report the number of assertionless tests, but won't call them failures.  I think that this is a good compromise while the CI process is fixed.

**Comment by Ducasse** [comment]
Hi guys 

I really like the change because you can CONTROL if your tests is good or not.
Right now we are plain BLIND. There are many tests that do not even work but are green. If this is what you want for Pharo then do not ask me to consider any tests in the future. 

Stef

**Comment by Ducasse** [comment]
I really like the explanation of andrew. Are we that blind?
I thought that smalltalkers were clever enough to see when a good idea was passing around. Because with this implementation we have the same old behavior and we can improve our tests confidence. Now if you reject this change, I will REALLY reconsider any effort in improving the quality of Pharo. I will focus on my side projects and do not care. You see I have the impression that each time we want to improve (comments for example) now tests we have conservationism flags and I DO NOT SEE any sound reasons. So think twice and take your responsibilities. 

Stef

**Comment by Ducasse** [comment]
I do not see why the fact that we can write silly tests in Java it can prove anything. 
I remember having to FIGHT with squeakers to get tests integrated and loaded into the image because of code bloat and we can remove tests in one line. So I'm ready to fight again because we MUST improve the situation. 

Stef

**Pull request closed without merging**
