### PR TITLE
Issue20164

### PR DESCRIPTION
**Pull request by akgrant43**
Cache the default working directory within a session as described in https://pharo.fogbugz.com/f/cases/20164/Caching-DiskStore-defaultWorkingDirectory

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
failing tests because of asUrl commit:

Gofer.Tests.GoferApiTest.testBlueplane    27 ms    1
 Gofer.Tests.GoferApiTest.testGemsource    6 ms    1
 Gofer.Tests.GoferApiTest.testHttpRepository    23 ms    1
 Gofer.Tests.GoferApiTest.testHttpRepositoryOverrideStoredCredentials    1 sec    1
 Gofer.Tests.GoferApiTest.testHttpRepositoryUseStoredCredentials    0.71 sec    1
 Gofer.Tests.GoferApiTest.testImpara    11 ms    1
 Gofer.Tests.GoferApiTest.testRenggli    6 ms    1
 Gofer.Tests.GoferApiTest.testRepositoryErrors    5 ms    1
 Gofer.Tests.GoferApiTest.testSqueakfoundation    5 ms    1
 Gofer.Tests.GoferApiTest.testWiresong    38 ms    1
 IssueTracking.Tests.PharoIssueTest.testTrackerUrl    22 ms    1
 Kernel.Tests.Processes.DelayMillisecondSchedulerTest.testMillisecondsToGo
 Monticello.Tests.MCDictionaryRepositoryTest.testCanCreateFileRepositoryFromUrl    7 ms    1
 Monticello.Tests.MCDictionaryRepositoryTest.testCanCreateFiletreeRepositoryFromUrl    3 ms    1
 Monticello.Tests.MCDictionaryRepositoryTest.testCanCreateFiletreeRepositoryFromUrlWithRelativePath    3 ms    1
 Monticello.Tests.MCDictionaryRepositoryTest.testCanCreateFtpRepositoryFromUrl    2 ms    1
 Monticello.Tests.MCDictionaryRepositoryTest.testCanCreateGitHubRepositoryFromUrl    2 ms    1
 Monticello.Tests.MCDictionaryRepositoryTest.testCanCreateHttpRepositoryFromUrl    2 ms    1
 Monticello.Tests.MCDictionaryRepositoryTest.testCanCreateHttpsRepositoryFromUrl    2 ms    1
 Monticello.Tests.MCDictionaryRepositoryTest.testCannotCreateDictionaryRepositoryFromUrl    0.18 sec    1
 Monticello.Tests.MCDirectoryRepositoryTest.testCanCreateFileRepositoryFromUrl    3 ms    1
 Monticello.Tests.MCDirectoryRepositoryTest.testCanCreateFiletreeRepositoryFromUrl    3 ms    1
 Monticello.Tests.MCDirectoryRepositoryTest.testCanCreateFiletreeRepositoryFromUrlWithRelativePath    3 ms    1
 Monticello.Tests.MCDirectoryRepositoryTest.testCanCreateFtpRepositoryFromUrl    3 ms    1
 Monticello.Tests.MCDirectoryRepositoryTest.testCanCreateGitHubRepositoryFromUrl    3 ms    1
 Monticello.Tests.MCDirectoryRepositoryTest.testCanCreateHttpRepositoryFromUrl    3 ms    1
 Monticello.Tests.MCDirectoryRepositoryTest.testCanCreateHttpsRepositoryFromUrl    3 ms    1
 Monticello.Tests.MCDirectoryRepositoryTest.testCannotCreateDictionaryRepositoryFromUrl    0.17 sec    1
 Monticello.Tests.MCRepositoryAuthorizationTest.testOverrideStoredCredentials    0.19 sec    1
 Monticello.Tests.MCRepositoryAuthorizationTest.testStoredCredentials    0.18 sec    1
 Monticello.Tests.MCRepositoryAuthorizationTest.testStoredCredentialsUsesMostSpecific    0.23 sec    1
 System.Settings.Tests.SystemSettingsPersistenceTest.testStoreAndLoadAllSystemSettings    0.38 sec    1
 Zinc.Resource.Meta.FileSystem.ZnFileUrlTests.testWindowsDriveNamesInFileUrl

**Comment by akgrant43** [comment]
Closing as I'll re-submit the PR without dragging in the asUrl commit (not sure how it got there in the first place).

**Comment by pavel-krivanek** [comment]
You do not need to close the pull request. You can just fix your branch.

**Comment by akgrant43** [comment]
Hi Pavel,

Thanks for the follow-up.

I originally:

1 forked the repository
2 cloned in Pharo
3 Created an issue branch
4 Applied the changes (which I was keeping in a changeset file)
5 "Create pull request..." from within Iceberg

I'm not sure why the asUrl changes got included (they aren't mine).  For pull request #96 I generated the PR from the github web page.

I'll have another go for my next PR and try and figure out what happened (if the problem re-occurs).

Thanks again,
Alistair

**Pull request closed without merging**
