### PR TITLE
20532 Proper categorization in Zodiac-Tests package

### PR DESCRIPTION
**Pull request by astares**
- method category "testing" is not for tests, use "tests"
- group some tests

https://pharo.fogbugz.com/f/cases/20532/Proper-categegorization-in-Zodiac-Tests-package

ONLY RECATEGORIZATION, NO CHANGE IN BEHAVIOR

### CODE REVIEW

**Comment by astares** [comment]
Ready to merge ...

**Comment by guillep** [comment]
This will most surely create a conflict with #379 .

Were this changes applied to Zinc smalltalkhub repository also?

**Comment by astares** [comment]
Zinc/Zodiac is not hosted on STHub. Sven has an own hosting server on 

http://mc.stfx.eu/Zodiac
http://mc.stfx.eu/ZincHTTPComponents

and the community can not access this one (except Sven). Do not know
if he is also using other repos (sthub, git). 

I took him on CC for the original Fogbugz issue. Maybe we need to contact
him separately.

**Comment by astares** [comment]
There also seem to be

https://github.com/svenvc/zinc
https://github.com/svenvc/zodiac

**Comment by estebanlm** [comment]
mmm... we need to think about this. 
and in any case, we can re-push later, with new file-format.

**Pull request closed without merging**
