### PR TITLE
20196-Remove-StringMorphEditor

### PR DESCRIPTION
**Pull request by pavel-krivanek**
https://pharo.fogbugz.com/f/cases/20196/Remove-StringMorphEditor

### CODE REVIEW

**Comment by guillep** [comment]
run tests

**Comment by pavel-krivanek** [comment]
bootstrap failed?

**Comment by pavel-krivanek** [comment]
run tests

**Comment by Ducasse** [comment]
Hi Pavel 

why do you want to remove it?
I do not see how it is related to the PluggableTextMorph and PluggableTextFieldMorph removal.
Stef

**Comment by pavel-krivanek** [comment]
Just not directly related cleanup. It is broken and not used.
For the PluggableTextMorph and PluggableTextFieldMorph I already had an experimental image where it was removed and replaced by Rubric alternatives, but we need to do it carefully

**Pull request merged**
