### PR TITLE
16196-Move-Zinc-Examples-to-a-different-package

### PR DESCRIPTION
**Pull request by estebanlm**
move class

### CODE REVIEW

**Comment by MarcusDenker** [comment]
We need to sync with the upstream maintainer: there are already quite a lot of fixes in Zinc that are not yet in Pharo7

**Comment by guillep** [comment]
Sync with Zinc is indeed needed but we need to open a separate issue for that. We also need to talk to Sven to move Zinc to Github. That will ease a lot of things.

**Comment by estebanlm** [comment]
it was also incomplete, I made this just for the demo :)

**Comment by svenvc** [comment]
Yes, another Zinc sync for 7 would be useful.

However, I have still not yet managed to do a simple contribution with the new git infrastructure, so I a hesitant.

**Comment by astares** [comment]
Sven: you should join Discord so things could be sorted out easier with chat (see http://pharo.org/community for Discord links).

**Comment by estebanlm** [comment]
@svenvc has you check Guille's instructions? https://github.com/guillep/PharoIntegrationProcess/wiki/Contribute-a-fix-to-Pharo

except by the fact you need to "fetch" from "origin" (when "origin" is pharo-project/pharo repository) before create the branch, is pretty much ok.

**Comment by MarcusDenker** [comment]
For me this is still too complex. I try every week to do a pull request with this description and it always is not a nice experience. Something is always wrong.

**Comment by estebanlm** [comment]
thing is 
1) you are cloning your fork and not pharo-project (it has to be the oposite)
2) you always need to fetch before (dev-0.6 will come with a "prepare for contribution" option who will take care about that)

**Pull request closed without merging**
