### PR TITLE
20680-Add-comments-to-FileSystem-packages

### PR DESCRIPTION
**Pull request by jecisc**
Add packages comments to FileSystem packages. 

See case 20680 : https://pharo.fogbugz.com/f/cases/20680/Add-comments-to-FileSystem-packages

Please, review them. My english is far from been good :)

### CODE REVIEW

**Comment by jecisc** [comment]
Hum… There is a lot of weird changes. I did not do them. Someone have an idea of what happened?

**Comment by pavel-krivanek** [comment]
I guess it will be Windows related

**Comment by pavel-krivanek** [comment]
Esteban confirmed that

**Comment by jecisc** [comment]
So… Should I just wait the next Iceberg release before contributing to Pharo again?

**Comment by jecisc** [comment]
The weird thing is that the changes are not the line returns but the deletion of a useless white space in end lines. I wonder what on Windows cause this.

**Comment by Ducasse** [comment]
So should we close this PR? And wait for the iceberg fix?

**Comment by jecisc** [comment]
I will redo the PR when I'll be able to commit on Windows :)

**Comment by Ducasse** [comment]
Sure did esteban mention if he fixed the issue.

**Pull request closed without merging**
