### PR TITLE
20697-Give-some-love-to-SocketAddress

### PR DESCRIPTION
**Pull request by svenvc**
SocketAddress is hardly used in the system.
It is possible to use it more and add some functionality to it.
Comments and test could be improved as well.

https://pharo.fogbugz.com/f/cases/20697/Give-some-love-to-SocketAddress

### CODE REVIEW

**Comment by svenvc** [comment]
How does one rerun a CI check ?

**Comment by jecisc** [comment]
@svenvc Only admin on the CI can do it I think. But as a user you can do a useless commit to force the relaunch. (by example delete a useless space at the end of a line and commit. Or better, correct a typo in a comment if you find one :P)

**Comment by pavel-krivanek** [comment]
you need to have rights to the CI to do it by your own. You can do a new commit to your branch with some unimportant change or simply write a comment to the PR, one of people who can do it will do it. I receive notifications about the PR updates so it should not take too long :-)

**Comment by svenvc** [comment]
Thanks!

**Pull request merged**
