### PR TITLE
Re-proposing Andrew's code modifying SUnit 

### PR DESCRIPTION
**Pull request by juliendelplanque**
Re-proposing Andrew's code modifying SUnit  to check dynamically if #assert: was call during execution or not.

This pull-request proposes to do the check depending on a setting that is unset by default.

To summarize, this should not break the CI.

### CODE REVIEW

**Comment by Ducasse** [comment]
Hi julien

What is the class method makesNoAssertion? it looks like it returns the boolean when reading the implementation but its name is confusing. 

Stef

**Comment by juliendelplanque** [comment]
@Ducasse it returns the Exception class used for such case. Others exceptions related to test running are also accessed like this.

See `TestResult >> #runCase:` where there is the exception handler.

**Comment by Ducasse** [comment]
Ok we will have to document this better then. 
We will do another pass once this PR is integrated.

**Comment by juliendelplanque** [comment]
Sure, another simple example of something to rework is the #printOn: method.

-------- Message original --------
Objet : Re: [pharo-project/pharo] Re-proposing Andrew's code modifying SUnit (#627)
De : StéphaneDucasse
À : pharo-project/pharo
Cc : Julien Delplanque ,Author


Ok we will have to document this better then.
We will do another pass once this PR is integrated.

**Comment by Ducasse** [comment]
I will have a look at the change... (load them and have a look later today).

**Comment by astares** [comment]
I would not change SUnit that way. Reasons were already explained in 
https://github.com/pharo-project/pharo/pull/554

Also this PR was rejected.

@juliendelplanque Can you ellaborate why you repropose it now again?

**Comment by Ducasse** [comment]
Torsten

Do you understand what this change is about for real?
You are judging but I do not think that you see the real value of this change.
And this change is really good because I can get a real value of a test
without changing the API of the tests. 
I WANT to know if our tests are good. Now I do not really care
if people want to stay blind and believe that we have green tests while they are WRONG!.
I do not care that people can write shitty tests in any language in the world. 
I care that we can get real added value. 

Stef

**Comment by juliendelplanque** [comment]
@astares, as @Ducasse said, this change is really valuable. Indeed, it allows to detect tests making no assertion which can be bad in some cases.

It already happened to me to generate tests, implement some of them, get distracted, click the "run all tests" button and tada my empty tests are green. I have a project with nearly 800 test methods (to test a parser) and with this modification I discovered that some of them were not implemented because I had no way to detect they were doing no assertion.

Now, this is a simple example but with @apblack, we discovered some tests for streams that were really wrong. These tests were simply bad written. For example a test was writing in a ReadWriteStream and then iterating on the results of the `#contents` message without sending `#reset` to the stream instance first. The assertion was inside the block used to iterate on the stream `#contents` (which was always empty).

Now, I understand that the first change was rejected, because it was breaking too much tests (but hey, some of those tests are green without the change but really broken). This new PR allows to disable this feature (it is disabled by default) from system's settings. I do not understand why it should not be integrated.

**Comment by jecisc** [comment]
The thing I do not like if the PR is integrated as it is that it is in contradiction to this rule: RBShouldntRaiseErrorRule

Now, I do not say this PR is bad. I just say that in its current state, it makes Pharo give two different recommendations.

**Comment by juliendelplanque** [comment]
@jecisc In this PR, me and Andrew added two methods to `TestCase` to allow not doing assertion in some tests but then you have to say it explicitly using `self deliberatelyDidNotAssert` or if you're writing a smoke test, you can use `self smokeTest`.

I think, it is better to say it explicitly if you want to write a test that fails if and only if there is an exception.

**Comment by astares** [comment]
@Ducasse  Your answer looks more like an emotional reaction and I still fail to see what your comment adds to the topic, especially when I ask Julien for his reasons as he was the one who opened the PR.

Let me tell you:
 - neither me nor others are "blind" or just "judge" without having reason if they like something or not
 - one thing you can take for granted: I know WHAT and WHY I'm commenting or agree or disagree 
   on a topic. 
 - please also stop argumenting with how much you invest as you would be the only one 
    who "cares". This is an open source and community project and many, many people care 
    to move Pharo forward. 

So let's discuss with real arguments and get back to the real topic of this PR. 

-----------------------------------------------------------------------------------------------------------------
@juliendelplanque thanks for clarification why you bring that topic back to the table.

I understood the reasons that we want to uncover tests that are badly written who might 
(but not necessarily must be) accidentially be seen as valid although they might have a problem. 

So you wrote we want to uncover and reveal such problems. This is a common goal for sure for all of us 
and we are fully in alignment on this on all sides.
  
But we have a different point of view on HOW we can achieve this common goal. The 
proposed PR under discussion still:

 - defines a test as wrong or bad when he has not one of the assert: variations called
   This is a redefinition of the original behavior of the unit testing framework(s)
 - forces people to use the assertions as only these would set the additional instance variable 
   "assertionMade" to true 
 - if people have use for one of the assert: variations in their test we would nonetheless
   force people to change their tests code 
    (they have to change test code explicitly and call messages like #deliberatelyDidNotAssert)
 - would introduce an incompatibility again (making it harder especially for packages
    ported/maintained in more than Pharo)


So on one side there is this proposed BENEFIT to "detect tests making no assertion which can be bad in some cases.". Note that you yourself wrote "some cases" which depicts that it is not a total benefit and 
only would reveals bugs under certain circumstances. 

But as this PR would willingly change the behavior of the test framework, add incompatibilities 
again and make it hard for others maintaining or porting code. So if we would merge it we would 
introduce and accept several DISADVANTAGES on the other side too. And to be honest I dont want
that when we could do better. 

So this is where I see our disagreement really is because I think we can together achieve our 
common goal/benefit to uncover bad tests in a way without introducing other and new 
disadvantages and without changing the testing framework itself.


Let's remember that 
 - we want to reveal "possible problems in test cases" that have no assertions called
 - there Juliens problem is that according to him so far there is "no way to detect they were 
   doing no assertion"

I think there is a way to solve this: we have a very nice code critics and rule system now in Pharo. 
So I would propose to add a new code critics rule to the system that is checking for exactly 
such test methods in TestCase subclass that do not use the assertion variations.
We could bring up a code warning if you have a testXXX method that is not sending one 
of the assertion selectors.

This way we would have only benefits without any disadvantages:
 - we would point the users to potential problems in their code
 - have a chance to reveal the discussed potential problems/bugs in the test methods
 - if the rule/critique does not apply one can ignore it in the manifest without changing
    the original test code
 - we would not need to change the test framework and continue to stay compatible

I guess this could satisfy requirements from all sides.

**Comment by juliendelplanque** [comment]
@astares, the problem with your proposition of a rule statically checking for methods that make no call to `#assert:` is that it will miss the "real bad tests". That is to say tests that are doing assertion in "conditional block" or in "loop blocks" that are never executed because the test is actually bad written (see the example I provided in one of my preceding message).

To my knowledge on this (with Andrew we investigated some of the potential bad tests revealed by the changes in this pull request), when there is no call to `#assert:` or similar it is generally on purpose. When the test method is bad written, there is a call to `#assert:` or similar but it never gets executed when running the test... So, to me, those cases are the most dangerous because there is no way to know that the test is wrong without dynamically checking for a call to assert since it will always be green even when no assertion was made...

So sorry, but the idea of creating a rule to do static analysis of test methods not calling `#assert:` or similar is absolutely not a good solution since it would only reveal implicit smoke tests. Tests where the logic is bad would still be hidden.

**Comment by astares** [comment]
It is true that a rule with static analysis might still not be enough to uncover some specialized hard cases
and for sure runtime/dynamic approaches can cover more. 
But then we need to check on concrete samples what we can do and should nonetheless see if there is a better solution with benefits only that can satisfy without too many hickups.

Unfortunately your preceding message are very vague and never point to a really concrete code example. You wrote about ReadWriteStream issues you found but you dont tell in which test class in which test method. Also I was not able to find out where to find the parser tests you spoke about.

If you want to others then you need to show more detailed what we uncover and "how bad" the test code needs to be written.  

So if possible please point to concrete code examples with problems you mentioned:

 - either in the image  
 - or to an available code project that one can load or check

We should all have a clear picture about what we speak here - because as I already outlined if the
PR is accepted and merged we also have to live with disadvantages (which we should nonetheless try to avoid).

With more concrete samples we might either find a way out or have a better reasoning for the change.

**Comment by juliendelplanque** [comment]
@astares, concrete example:

This test is found to make no assertion during runtime (using the changes in this PR):
```
FloatArrayTest>>testPrintOnDelimiter
	| aStream result allElementsAsString |
	result:=''.
	aStream:= ReadWriteStream on: result.
	
	self nonEmpty printOn: aStream delimiter: ', ' .
	
	allElementsAsString:=(result findBetweenSubstrings: ', ' ).
	1 to: allElementsAsString size do:
		[:i | 
		self assert: (allElementsAsString at:i)=((self nonEmpty at:i)asString).
			].
```

By looking at it a little, you can see that it is because the `result` temporary variable should hold `aStream content` but it is not done. Nevertheless, the test is green but not because the functionality is well tested and works well but because this test is wrong.

An easy fix for this test would be:
```
FloatArrayTest>>#testPrintOnDelimiter
	| aStream result allElementsAsString |
	result:=''.
	aStream:= ReadWriteStream on: result.
	
	self nonEmpty printOn: aStream delimiter: ', ' .
	result := aStream contents.
	allElementsAsString:=(result findBetweenSubstrings: ', ' ).
	1 to: allElementsAsString size do:
		[:i | 
		self assert: (allElementsAsString at:i)=((self nonEmpty at:i)asString).
			].
```

Luckily, it is still green. But it might not always be the case.

**Comment by astares** [comment]
Yes - dynamically checking the assert: call would reveal this particulare one.

But you have to admit is a very specific case nonetheless: This test's aim was to ensure proper working of #printOn:delimiter: which is done very badly. The basic problem already is that the test method does not work with an explicit expected result.

The author of the test tries to write the code very generic and checks for an implicit result. If for instance if #printOn:delimiter: would be written like 

```Smalltalk
printOn: aStream delimiter: delimString
	"Print elements on a stream separated
	with a delimiter String like: 'a, b, c' "

	self do: [:elem | aStream print: elem] separatedBy: [aStream print: delimString].
	self do: [:elem | aStream print: elem] separatedBy: [aStream print: delimString].
```
		
the test would still be green, but the methods outcome would not be satisfyable at all ....
Providing directly a more concrete expected result would have been better - which would also
make the code shorter and also easier to undertand. But lets not get too offtopic.

Even when it was written poorly: how many of such cases do we really have? 
Will a single case already justify the disadvantages? Do we have more similar effects 
that could be revealed? How many of them?

**Comment by apblack** [comment]
> Even when it was written poorly: how many of such cases do we really have?
Will a single case already justify the disadvantages? Do we have more similar effects
that could be revealed? How many of them?

I found dozens of such cases with a cursory look!  We can't know how many others there are until we look.  That's the whole point of tracking tests that make no assertions: to prompt us to look!  

The bad test that @juliendelplanque  showed above was reported in an issue in _2013_.  But so long as it ran green, no one was motivated to fix it.  Red tests provide this motivation.

**Comment by astares** [comment]
>We can't know how many others there are until we look. 

Yes - but we can look already now by checking in a standard image just applying the change.
Even when the PR is not yet merged. Right?

**Comment by juliendelplanque** [comment]
@astares yes, you can but you need to check each method that does no assertion by hand to determinate if it is done on purpose or not.

**Comment by astares** [comment]
We need to look anyway when we merge the change, no?

**Comment by juliendelplanque** [comment]
Indeed but what is your point? I think it will take some time to resolve all of them.

**Comment by astares** [comment]
So you already know how many problems this change will reveal? If not where is the problem in checking in advance to see if the change is really worth the disadvantages.

**Comment by Ducasse** [comment]
@astares 
Why do you bullshit me on the area that my reaction would be emotional. 
I think (as expert in software engineering, software analysis, static analysis,
8th ranked inria research ... do you want my cv?) that this extension of SUnit is really valuable. 
I think that your stance is not good because you do not listen the argument of Julien and Andrew as they should. 
I think that their approach is really valuable and there is nothing emotional in my statement. With their approach we can spot problems that are not detectable otherwise. And this changes will go in Pharo. 

Stef

**Comment by Ducasse** [comment]
Julien I'm starting to get annoyed by this conversation. It seems that Torsten wants to argue for the sake of arguing. So may be we should mute this thread. May be this is even what Torsten wants to achieve: show that we can not endlessly argue for useless point.

**Comment by Ducasse** [comment]
Torsten the fact that you propose a static analysis rules shows to me that you did not understand clearly what we are trying to address: we want to know whether at runtime an assert is executed. Then I do not see how the change is modifying the framework it is not since when you do not activate it you get EXACTLY the same behavior than before. So I do not understand your point. 
To me it looks like you argue for the sake of arguing.

**Comment by apblack** [comment]
@Ducasse wrote:
> when you do not activate it you get EXACTLY the same behavior than before

You get _almost_, but not exactly, the same behaviour as before.  What is true is that exactly the same tests will pass and fail as before.  The difference is that the number of tests that make no assertion is _counted_, and reported in the message, e.g., `19 test run, 2 tests made no assertion`. This is intended to make you curious.  You might say, “oh yes, those are my two smoke tests.  I should mark one with `self smokeTest`, and I should just remove the other one, since it’s dominated by a newer test.   Or you might say “that’s odd, why is one of my tests not making an assertion?”, look more closely, and find a buggy test.

**Comment by astares** [comment]
>
>argue for the sake of arguing
>... do you want my cv?

Do you really think I want to spend my time here just to have a pleasant discussion with you, bug you, fight with nonsense arguments or fill github with a long thread? And do you really think a reputation will automagically answer or overrule the doubts and questions raised before? 

Meanwhile on PR 554 you have added even more comments which to me still have more emotional nature than staying on topic and contributing to a real solution:

>If this is what you want for Pharo then do not ask me to consider any tests in the future.
>...
>Now if you reject this change, I will REALLY reconsider any effort in improving the quality of Pharo.

I'm really disappointed by this behavior. Would'nt fighting with arguments and improvements on the code for the PR be better than your "I'm the expert here" or "if I dont get what I want I stop writing tests or even quit" behavior? 

The PR 554 was already rejected and there were clear reasons. One strong reasons what that we get a lot of failing tests. Now this PR improved by having a setting which will at least address some parts. 

>we want to know whether at runtime an assert is executed. 

I know and this was completely understood from my side. If you reread the thread you will see that I already agreed two days ago that only dynamic solution reveals the case described by Julien (which so far is the only concrete case described).

>So I do not understand your point.

Maybe I repeat so we get back to a common understanding and maybe some examples can help
to show you the concerns I would still raise:

 1. There are some bugs in badly written tests which are hard to reveal with the current
      way the tests are run. They are green although problematic and we assume situation
      is fine while it is not.

      What we know so far is that such kind of bugs have in common that the test code might not 
      call the 
               - #assert:
               - #assert:description: 
      or other assertions keywords (who internally call these two messages).

      So this is a fact and nobody have any doubts that such cases exists.

2. We agreed already on all side on the common goal to improve and find a way to uncover these
    hidden problems.

    So it seems more a difference or misunderstanding in HOW we achive the goal than in the 
    goal itself.

3. We also know and agree that we can not solve the problem easily with a static quality rule
    as the test message might send an assertion but during runtime the
    code flow can go a path/route in the method without passing/calling the assertions. 

4. Julien depicted so far a single test case which was badly written as a single concrete
    case where we have this problem. This is a case from 2013. 
    
    Now:
     - Julien was able to give a single concrete example #testPrintOnDelimiter for a bad test
     - Alan mentioned he found dozens of such cases (without giving further concrete examples)

    I asked for more concrete examples to see if the solution really fits already.
    Stef already seems to be fine - at least he decided "this changes will go in Pharo".

   Julien wrote "I think it will take some time to resolve all of them" - so he expects to reveal
   many hidden bugs while I just said that we do not have a clear number other than the 
   single concrete case.

               => I still do not understand where is the problem in giving one ore two more 
                   concrete examples. Especially when Alan mentioned he has dozens of such cases 
                   and  Julien expects so many of them that it will take a long time to fix them.
                   
    So we still do not know if these problems follow a certain pattern that might help
    to  improve the proposed PR and give us **more concrete hits** afterwards.

  5. So I asked if someone already took a recent standard image and checked in advance
      with the proposed PR. 

     The answer from Julien (at least for me) was unsatisfying:
            - Julien did not tell us anything if he really checked in a recent image (so I guess he did not)
            - he only said that one can do that but looking at each method is a manual job to decide
              if the test is not using assertions by intention 

             => I fail to see where is the problem in checking in a recent image concretely already
                  and in advance looking if we have many false positives or concrete revealing of 
                  bugs. 
                  Would'nt this give us more trust also on the effects of the PR? 

 6. You could now argue "who cares on the numbers. If it would reveal a single bug or
      a bug introduced in the future it would already pay off". To some extent I would agree
      but also look at some of the downsides:

  a)   Already in my comments in PR #554 I explained that in SUnit it is totally valid to write
        tests without a call to a single variant of #assert:

        So tests like

```Smalltalk
               testFoo
                     "do nothing"
```            
    which is an empty test is valid and green not only in Smalltalk. 

  b) One might now answer "why should we care on empty tests" or 
      "compatibility with shitty languages"

      But for me when working on a project it is not uncommon to just "uncomment" the
      contents of a failing test because I want to be green for CI and work on the test then
      later. 
 
       With the PR as it is now these methods would need a manual review with the
       settings on although one is hunting for the other "assertion problem" bugs. 

   c) Also tests like

```Smalltalk
testFoo

	self should: [ Compiler evaluate: '3+4' ] raise: Exception
```
       would come up as "problematic cases" nonetheless. Sometimes you just write
       a test method like this:

```Smalltalk
testSomethingIsNotBroken
      SomeClass someAction
```
     again without any assertion. It is perfectly valid but would be manually looked at.

    d) If you want to have more concrete examples also from the standard Pharo image:

```Smalltalk
 testNew
	self targetClass new
```

      This one would fail many times (as it is an inherited test) for many cases (for all ClassTestCase 
      subclasses to be precise). 

     So all these would come up (although fully valid in the sense of SUnit) as problematic cases 
     instantly when the change is included as it is today and the assertion check setting would be 
     enabled. 

    Also it would confuse the user as the test runner would show these as "x test making no assertions"
    as if one would have to work on them and add assertions artificially although not needed.

 8. You can now argue that they only fail when the setting is enabled. Yes - this is true and I agree
     to that as well. But it will nonetheless will have an effect:

      Think of a developer who is enabling the setting and runs the tests as he also wants to 
      be safe from our "assertion bugs". Many tests will fail with the settings on - but not all
      of them will have the "assertion problem" we try to reveal with this change. 

      So he also  must manually review each test (which is a exhausting job on itself). But if he do not
      want to do it over and over again he need to separate the "already reviewed" cases from the 
      "not yet looked/reviewed" tests. Right? 

     Because of this our PR proposes a new method called #deliberatelyDidNotAssert to mark them
     and not flag them in the future again.

     Which means our developer needs to modify each reviewed tests with an additional message 
     send:

 ```Smalltalk
testNew
        self deliberatelyDidNotAssert.
	self targetClass new
```    

      => This is what I still do not like on the change:

              a) Because with the setting enabled we change the behavior of the unit framework
                   to not accept perfectly valid tests anymore
    
              b)  Also over time one is forced to manually adopt these tests although they are 
                   perfectly valid to reduce the number of failing tests - because when the setting 
                   is enabled you want to avoid to look again and again at the same perfectly 
                   valid cases

              c) Such modifications might also bring "multiplatform" porters like Seaside 
                  developers into distress as they would like to reveal bugs on one side but not 
                  change there tests to use selectors like #deliberatelyDidNotAssert which
                  are only in the Pharo's SUnit variant.

7. Julien wrote:

>it allows to detect tests making no assertion which can be bad in some cases.
 
     So the basic problem is that a test found can be bad but not necessarily must be bad.
     Also we know from some of the points above that it will classify many perfectly valid
     tests as problematic.   

     For me this is already reason enough
          - to ask for more examples of buggy tests to see if we find a pattern or other 
            to improve the solution
          - to not (yet) include it/merge it right away in its current code state as of today
            
8. To understand me correct: I see value in finding these bugs and also would like to 
     have a mechanism included to reveal them. 
     Nobody want to reject it again but that we need to find a way to reduce or kill the 
     drawbacks.

Currently as of today the code classifies ANY test method that does not send an assertion
as bad. 

One improvement / compromise could be that it classifies only these tests as
bad methods that REALLY send an assertion message AND then do NOT CALL it.
This would be a combination of the static "sends assertion message" and the "assertionMade" flag.
 
It would avoid lamenting about valid test cases as described in 6a - 6d and classifying them as problematic. This way we would get IMHO better hits and limit the problematic classfied cases at the same time.

**Comment by Ducasse** [comment]
Andrew 

I do not remember if we included or not the change in printing the results. To me the printing does not change the behavior of a test.

Stef

**Comment by Ducasse** [comment]
Torsten

My last comment on this thread.
- I do not understand what is your point. 
- Julien took into account the remarks we did him during the last spring. 
- Trying to reach perfection is the best way to achieve nothing at the end. 
- We will do another iteration together and we will integrate this changes so that we
can spot and incrementally fix all the problems that exist in the system.

I agree with the following so we can do it. 
- One improvement / compromise could be that it classifies only these tests as
bad methods that REALLY send an assertion message AND then do NOT CALL it.
This would be a combination of the static "sends assertion message" and the "assertionMade" flag.

It would avoid lamenting about valid test cases as described in 6a - 6d and classifying them as problematic. This way we would get IMHO better hits and limit the problematic classfied cases at the same time.

The process that I see is that in development you turn the flag on
- you should be notified if you write a test without assertion and if your assertions are not executed. 
- then in reaction you will annotate the test with no assertion with a pragma stating that it is a false positive and the system should not consider them as bad.
- for the test with non executed assertions, they are flag as problems. 


Stef

**Comment by Ducasse** [comment]
I think that smokeTest should be tagged with a pragma and not a self smokeTest methods like that there have no effect when loaded in a different version of the framework.

**Comment by astares** [comment]
>I do not understand what is your point

Currently how the PR was proposed one would have to change his tests to explicitly and additionally call #deliberatelyDidNotAssert and with this it would make the test unusable to run on other SUnit version or platforms. This would make life hard for developers who either have test packages in different Pharo version or who port between Smalltalk/other SUnit platforms.
I just want to avoid that and I'm sure we can.

>then in reaction you will annotate the test with no assertion with a pragma stating that it is a false >positive and the system should not consider them as bad.

Yes - now we are talking!!! This sounds much better and could solve it. Using a pragma would be fine for me as it is not as intrusive as the current/old way the change was proposed. It would allow to continue to run tests on different versions of the framework or other platforms. We can agree upon this easily.

To summarize the compromises and needed changes to meet the common goal and
avoid side effects:

1. We classifies only these tests as bad methods that REALLY send an assertion message 
    AND when running do NOT CALL this assertion.

2. We use pragmas to annotate tests methods who send assertion but where BY INTENTION
    the assertion messages must not be called at runtime. Same for smokeTest.

Then we would be really aligned. If this could be realized I happily vote for the merge of the change/PR and will also help you sorting out the found issues or annotating tests when necessary.

**Comment by Ducasse** [comment]
What you should understand is that instead of saying No this is bad. 
I prefer to see what is really nice and this is why I told julien to repackage their changes. Being positive and open to improvement is really important. 
Now for the record (we could use a message and not a pragma - people just have to write good tests if they want to port their code to other systems). So this is not the kind of extensions that change SUnit because it is backward compatible. 
But indeed having a declarative way is better. 

I would 
- add a pragma for smokeTest
- I do not get why by construction people would use an assert: that should not be called.

We should do a pass and code review because some methods looks not intention revealing to me. I plan to sit with julien and look at the code with him. 

Stef

**Comment by Valtena** [comment]
Hi,

Why do we want to use pragma to assert than a method doesn't raise an exception instead using a SUnit's assertion? The pharo community trashtalk JS for the inconsistency (on operators + - for exemple), so why introduce one here?

#shouldnt:raise: make job correctly. This show the error encountered for debug. This is consistency  with the rest of SUnit.  But it's say: "that should not be called" ! Yes, but it's more accurate to say "Error should not be raised" than "that method should finish without trouble". But what is a trouble?  an Exception can be see like a normal ending.

I'm not against the usage of pragmas for some cases. For example, if, in a test, I want to say: "don't run this test because it is not finish", in this case, a pragma but be ok. After all, it's a test yet now.

**Comment by Ducasse** [comment]
We are working on a new version with Julien. We will come back to it when he is back from his trip. I close the discussion from now. 

@valtena. An exception does not help in our case. 
We want a static annotation so that tools can manipulate the code. 

Stef

**Pull request closed without merging**
