### PR TITLE
20557-Update-Zinc-and-Zodiac

### PR DESCRIPTION
**Pull request by pavel-krivanek**
https://pharo.fogbugz.com/f/cases/20557/Update-Zinc-and-Zodiac

merge packages:
Zodiac-Tests-SvenVanCaekenberghe.18
Zinc-Character-Encoding-Core-SvenVanCaekenberghe.54
Zinc-Character-Encoding-Tests-SvenVanCaekenberghe.35
Zinc-HTTP-SvenVanCaekenberghe.469
Zinc-Resource-Meta-Core-SvenVanCaekenberghe.65
Zinc-Resource-Meta-Tests-SvenVanCaekenberghe.38
Zinc-Tests-SvenVanCaekenberghe.243
Zinc-Zodiac-SvenVanCaekenberghe.40

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
The bleeding edge. The last stable version (2.8.8) is from 16th of June 2017 but some important bugfixes were done recently.

**Comment by guillep** [comment]
This will probably conflict with #355 ?

**Comment by astares** [comment]
Note that the FogBugz issue mentions the following repositories

http://mc.stfx.eu/Zodiac
http://mc.stfx.eu/ZincHTTPComponents

but there is also 

https://github.com/svenvc/zinc
https://github.com/svenvc/zodiac

**Comment by pavel-krivanek** [comment]
Marked as official stable version 2.8.9 by Sven

**Pull request merged**
