### PR TITLE
20209-Unify-the-way-to-obtain-package-manifests

### PR DESCRIPTION
**Pull request by Uko**
first Pharo PR :)

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
Congrats! ;-)

**Comment by pavel-krivanek** [comment]
https://pharo.fogbugz.com/f/cases/20209/

**Comment by Uko** [comment]
Why of why do the tests fail :(

**Comment by pavel-krivanek** [comment]
It is currently standard behavior. It's not related to the PR content

**Pull request merged**
