### PR TITLE
20306-Make-SUnit-loadable-by-Hermes, case 20306

### PR DESCRIPTION
**Pull request by pavel-krivanek**
https://pharo.fogbugz.com/f/cases/20306/Make-SUnit-loadable-by-Hermes

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
Summary:
- add very simple PerformMessageCommandLineHandler package that can execute messages without need of having compiler in the image. This handler then enables to use commands like
```pharo bootstrap.image perform TestCase runAllAndLogResult```
This package is now not loaded. Only present in the repository ready to be exported together with SUnit and used by CI jobs
- extensions of RGMethodDefinition are now standard local methods. It is probably (at least for now) better than to create a new package for them
- BadHasher was modified to do not depend on Random-Core
- optional dependency on ChangeSet
- TestAsserter has flattened TAsserter methods. The TAsserter is still present but not directly used by SUnit. Later we can move it to separate/different package to do not need traits support for SUnit-Core at all

**Comment by tesonep** [comment]
@pavel-krivanek Are you thinking in adding a new step in the Jenkinsbuild process??

**Comment by pavel-krivanek** [comment]
Yes, but not directly now. We should be able to run tests directly in every step of the image building process. Including the first bootstrapping step. It will not be a step in the building chain but only a validation step.

**Comment by guillep** [comment]
but if that validation does not run, who looks at it? I vote to add a validation step in the jenkins file. Otherwise it will just rot.

**Comment by pavel-krivanek** [comment]
ok

**Comment by pavel-krivanek** [comment]
For the beginning we will run only few tests in SUnit-Core, I tried SUnit-Tests but we have too many errors related to the classes deletion. 
The PR introduces InitializePackageCommandLineHandler that will enable us to initialize RPackage organizer and protocols without need of a compiler.

**Comment by pavel-krivanek** [comment]
integration into the process (jenkinsfile) not finished

**Comment by pavel-krivanek** [comment]
Reviewed in pair by Pavel & Marcus

**Pull request merged**
