### PR TITLE
Yield the CPU longer

### PR DESCRIPTION
**Pull request by zecke**
The work of the idle process is to run when no other smalltalk process is
runnable. And the process will use a primitive to yield execution for a given
amount of microseconds. The VM will either pick the closest delay to expire
or the timeout provided and yield execution. It will resume earlier in case of
I/O.

Pick 50ms as this is the time WorldState will update in server mode. In the
future we can increase it to minutes.

### CODE REVIEW

**Comment by zecke** [comment]
So instead of having to wake-up every 1ms.. we can now sleep a bit longer.. if this behaves well we should increase it to more... (until there is a primitive for yield for forever)

**Comment by astares** [comment]
https://pharo.fogbugz.com/f/cases/20425

**Comment by zecke** [comment]
@noha

**Comment by guillep** [comment]
To me it looks ok and tests ran green.

We were checking how this would work in case of semaphores, delays and async IO and it looks like everything is ok in the VM. My only doubt is on windows, we should check it.

@pavel-krivanek is going to test on windows I think.

Could we discuss it on the mailing list at least?

**Comment by pavel-krivanek** [comment]
On Windows VM I tried some extreme value and it had no impact on the system speed (at least feel of it) so this PR should be safe.

**Comment by zecke** [comment]
Can you see CPU saving as well?

@pavel-krivanek See my latest mail to VM-dev. I think there is a race condition in the Windows VM that could lead to missing a wakeup event.

@guillep I sent an email prior to ESUG, feel free to follow up there and I can explain how things work on Windows, Mac and Unix/Linux.

**Comment by zecke** [comment]
@pavel-krivanek Please note that likely the code will only be executed if you spawn a new idle process (E.g. ProcessorScheduler startUp / or image save/restore)

**Comment by pavel-krivanek** [comment]
@zecke of course I restarted this process ( ProcessorScheduler startUp)

**Comment by guillep** [comment]
I saw the discussion in the vm list, but most pharo people is in pharo-dev :) I just believe people in the pharo list that is not reading the PR list should be aware of this.

**Comment by astares** [comment]
http://lists.squeakfoundation.org/pipermail/vm-dev/2017-September/date.html

**Comment by zecke** [comment]
http://lists.pharo.org/pipermail/pharo-dev_lists.pharo.org/2017-August/131212.html

**Comment by estebanlm** [comment]
so, what we do with this?

**Comment by zecke** [comment]
Merge it? Slowly increase it? The only issue I see is on the Windows VM (http://lists.squeakfoundation.org/pipermail/vm-dev/2017-September/025765.html) but no one cared so maybe let's merge and see? Slowly increase the yielding time?

**Comment by estebanlm** [comment]
I will merge and keep an eye on it ;)

**Comment by estebanlm** [comment]
ok, I will need to revert :/
I don't know why it fails

**Comment by zecke** [comment]
Can you point to the jenkins output?

**Comment by bencoman** [comment]
On Tue, Oct 17, 2017 at 6:12 PM, Holger Freyther <notifications@github.com>
wrote:

> Can you point to the jenkins output?
>
https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/development/204/console

**Comment by zecke** [comment]
What can we do about it?

**Pull request merged**
