### PR TITLE
Updated Fuel to 2.2.0 with the 64 bit adaptations

### PR DESCRIPTION
**Pull request by theseion**
https://pharo.manuscript.com/f/cases/20120/Fuel-is-not-64bits-ready

### CODE REVIEW

**Comment by noha** [comment]
Max, can you accept the PR of Pavel so we can trigger another build?

**Comment by theseion** [comment]
Which PR are you talking about? I couldn't find any that would concern me.

**Comment by theseion** [comment]
Sorry for that. For some reason i wasn't notified about the PR.

**Comment by noha** [comment]
That was the only reason trying to notify through this ;)

**Comment by astares** [comment]
Be aware of this: https://pharo.fogbugz.com/f/cases/20961/Broken-Tonel-file-in-FuelTests-in-pharo-project-pharo-repo

**Pull request merged**
