### PR TITLE
20647-SortFunction-should-be-composable

### PR DESCRIPTION
**Pull request by nicolas-cellier-aka-nice**
Make SortFunction composable

https://pharo.fogbugz.com/f/cases/20647/SortFunction-should-be-composable

Note: impossible to use iceberg to do the commit
incomprehensible interface / unexpected failures / unclear error messages

### CODE REVIEW

**Comment by dionisiydk** [comment]
Also let's choose what to use inverse or reverse.
Because now there is ReverseSortFunction and #inversed message to get it. They should be same.

**Comment by nicolas-cellier-aka-nice** [comment]
- agree for reversed vs inverted: my idea whas to use `reversed` like in Collection because

    (people sorted: "name ascending reversed)
      = (people sorted: "name ascending) reversed

- for uniqueInstance, I don't know...
  my POV is that client should not care.
  the fact to have a uniqueInstance is a space optimization

**Comment by dionisiydk** [comment]
I am fine with #reversed.

But #new should create new instance or raise error. Because message should do what it means in the name. Instead it could lead to unexpected behaviour. Maybe it's not important for that case but it is my general feeling. Also for clients we can have more nicer form:
```Smalltalk
SortFunction default
```

**Comment by nicolas-cellier-aka-nice** [comment]
Maybe you are right
> you can cheat as long as you don't get caught
is a pattern asking for trouble

**Comment by dionisiydk** [comment]
Few notes:
- can you also add constructor to ComposedSortFunction like #basedOn: or #on:? It is better style than calling "new baseSortFunction:"  
- I think "SortFunction default" can be useful (I not noticed accessor for Default). It allows following expressions:
```Smalltalk
#(one nil two) sorted: SortFunction default undefinedFirst.
#(one nil two) sorted: SortFunction default reversed undefinedFirst.
```

**Comment by dionisiydk** [comment]
Hi Nicolas.
Do you plan to apply here boolean sort function as we discussed in thread? 
Or we can create another issue for this.

**Comment by nicolas-cellier-aka-nice** [comment]
Hi Denis,
I'd suggest opening another issue. Small steps :)

**Comment by dionisiydk** [comment]
Ok, let's integrate

**Comment by pavel-krivanek** [comment]
test failure not related
```
MacOS32.OmbuTests.OmDeferrerTest.testExecuteOnceAfterSchedulingMultipleTimes
```

**Pull request merged**
