### PR TITLE
18764-Remove-external-dependencies-from-Kernel-Tests

### PR DESCRIPTION
**Pull request by pavel-krivanek**
https://pharo.fogbugz.com/f/cases/18764/Remove-external-dependencies-from-Kernel-Tests

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
We should not merge this PR as is because we need to fix the baselines to contain the new package

**Comment by Ducasse** [comment]
Looks good. Now I could not see how the reference to file went to Directory.

**Comment by guillep** [comment]
run tests

**Comment by pavel-krivanek** [comment]
strange, the monkey complains about merge conflicts

**Comment by pavel-krivanek** [comment]
redone as https://github.com/pharo-project/pharo/pull/365

**Pull request closed without merging**
