### PR TITLE
20384-Converted-rules-to-Renraku-architecture-2

### PR DESCRIPTION
**Pull request by Uko**
Let's try this one, it should work

### CODE REVIEW

**Comment by MarcusDenker** [comment]
The failing test are now:

MacOS32.Announcements.Tests.Core.Tests.WeakAnnouncerTest.testWeakDoubleAnnouncer
Windows32.Announcements.Tests.Core.Tests.WeakAnnouncerTest.testWeakDoubleAnnouncer

**Comment by Uko** [comment]
I will look into that

**Comment by pavel-krivanek** [comment]
That's timeout issue 
```
Process>>pvtSignal:list:```

**Comment by pavel-krivanek** [comment]
https://github.com/pharo-project/pharo/pull/509

**Pull request merged**
