### PR TITLE
21094 Super tearDown need to be called as last message in tearDown of Metacello

### PR DESCRIPTION
**Pull request by astares**
https://pharo.fogbugz.com/f/cases/21094/Super-tearDown-need-to-be-called-as-last-message-in-tearDown-of-Metacello

### CODE REVIEW

**Comment by dalehenrich** [comment]
@astares I would think that a change like this should be made in the official Metacello repository as Pharo should be regularly doing pull requests from the official repository to pick up other bugfixes ... I was under the impression that was supposed to be the process at any rate...

**Comment by astares** [comment]
@dalehenrich Yes. Did you see https://pharo.fogbugz.com/f/cases/21094/Super-tearDown-need-to-be-called-as-last-message-in-tearDown-of-Metacello

and  https://github.com/Metacello/metacello/pull/479 ?

**Comment by dalehenrich** [comment]
yes but I am looking at the root cause for having to move the tearDown method to the end ... if I am going to write portable tests I need to understand why some "cross-platform" tests are suddenly sensitive to the placement of the #tearDown method ...so far I have found nothing but "it needs to be last" and I would like a little bit more info as to why ...

**Comment by dalehenrich** [comment]
... and I would expect that if the patch was made to the master Metacello repository it wouldn't be necessary to make a (presumably duplicate) set of changes in this repo ... as it should pick up the changes from the master Metacello project

**Comment by astares** [comment]
You could have bad side effects if you call tear down from the superclass first. So it is recommended to use LIFO principle (especially for deallocation) and we ensure this order now with a lint rule as well as a test (same for setup where a super setUp should be done first)

I do not have a written reference at hand now for original SUnit but this is common practice meanwhile in testing. 

Here is an example:
https://developer.android.com/reference/android/test/ServiceTestCase.html
"After each test method finishes, the test case calls the tearDown() method. This method stops and destroys the service with the appropriate calls, depending on how the service was started. If you override tearDown(), your must call the super.tearDown() as the last statement in your override."

https://developer.apple.com/documentation/xctest/xctestcase/understanding_setup_and_teardown_for_test_methods

Google it and you will find others too.

Reintegration of external packages is slower and requires a fully new version each time. Now many places have been fixed in P7 since the last three weeks regarding this and other cleanup topics and there are/will be release tests to ensure we stay clean in the future. 

Waiting for a new Metacello version would slow this down. To my knowledge it is not directly integrated in the bootstrap but synched from time to time. But I would like to push cleanups forward.

While you can work full time I only can invest when there is some spare time so I need to move to get all these cleanings done. Hope you can understand this and sorry if I missed to inform you earlier on a separate way. I noted it in the bug as you can see and thought you will review the PR anyway.

**Comment by dalehenrich** [comment]
So is this a cleanup for general purposes or is there an explicit issue being solved ... it seems urgent, so tests that have run for years (close to a decade now) are suddenly failing? This is always suspicious to me ... but if you don't know why this is being done then the Metacello tests in the main repository are passing ... I was just hoping that there was a real reason behind this urgent change ...

**Comment by dalehenrich** [comment]
Well the argument that waiting for the Metacello PR doesn't  quite hold water, since it seems that the master project merged before the pharo project anyway ... the pharo version of Metacello has drifted into brokenness in the past because the master repository was ignored and it seems that this will happen again ... oh well...

**Comment by astares** [comment]
I agree that there are some more rules are missing after the move to git and bootstrap and the situation with mixed external/internal packages is not ideal. If I did a mistake then tell me what the official process for Metacello is and where this is written so that I can making a failure twice. 

You might be satisfied with green tests - I'm really not because this is only one side of the coin. We will and need to raise the quality bar of the code - especially for the main image.

While Smalltalk usually should be nice and readable we have lots of trivial violations to lint rules (like missing super setUp calls, unused temporaries, unused methods, uncommented classes). Also lots of typos.

On the other hand we would like to call our systems "professional" while even in communities like Java people follow such simple best practices as the one we discuss here: https://coderanch.com/t/445846/super-teardown

But enough time spend in explaining ... would rather spend my time on fixes and cleanups

**Comment by dalehenrich** [comment]
The process that I would prefer would be to make all changes in the master Metacello/metacello repository and then have the consumers of the project fork arrange to use the latest version of the master for every build ... to do otherwise puts us back where we a couple of years ago, where I had bug fixes sitting in the master repository that were not incorporated into the Pharo builds ... this went on for years ... and having metacello apparently embedded in the pharo repository means that individual developers who are interested in only getting the latest Metacello can easily do so ... as it stands now, I'm not even sure that an individual developer can even load the master Metacello version into Pharo ... which is not how it is supposed to be ...

Yes and having to make changes in two different places takes more "precious" development time as well ..

**Comment by jecisc** [comment]
Always integrating latest master version of Metacello can be dangerous in the way that Pharo do not really control what will be integrated with each commit while currently one commit = one change with a bugentry in fogbugz. 

One better way can be the one of Iceberg management.

Iceberg release new version via github's tags and once a new tag is released a PR is do to Pharo to change the version of Iceberg to load. 

Here is an example: [https://github.com/pharo-project/pharo/pull/643/files](https://github.com/pharo-project/pharo/pull/643/files)

**Comment by dalehenrich** [comment]
Dangerous? I do not merge anything onto the master branch unless it has passed all tests ... If pharo would prefer to pick up the latest tag, then I can certainly arrange to tag each of the merges into the master branch ... and I would be willing to do that if that meant that pharo would finally stay (relatively) up-to-date with the Metacello master branch for each build ... who would be responsible for updating that [homongous file](https://github.com/pavel-krivanek/pharo/blob/f37318837aa0c9abc3911aed219b2d416d3faaa8/src/BaselineOfIDE/BaselineOfIDE.class.st)?

**Comment by jecisc** [comment]
I know you do not merge anything that did not passed the tests. But three things:

- Even if a fix pass all tests and seems harmless, we cannot be sure at 100% there will be zero problem with it.
- What if Pharo badly use Metacello somewhere and use a private method that is remove later in Metacello's master? 

If one of those two cases happen, it will be easier to find the problem in a commit named "Update to Metacello 1.3.2" than in a commit named "Integrate Calypso" if it was done exactly when Metacello merged a new PR. 

And the third point is that currently it is possible to re-build a version of Pharo from a certain commit I think. If we add dependencies to branches and not tags, it will no longer be possible. 

I don't know if it will be really useful, but maybe later peoples will need some hotfix on specific Pharo's versions? 

Those are the reasons I would prefere to reference tags instead of branches. 

Then the question of who would update the baseline. If nobody wish to take this role I can subscribe to Metacello and do it when I receive a mail about a new tag. 
BUT, I don't have the time right now to change the way Pharo loads Metacello to manage it like we manage Iceberg. 

I would like to add Guille, Pavel, Esteban, Pablo to the conversation to get their ideas on the subject but I am on phone and I cannot do it right now :(

**Comment by pavel-krivanek** [comment]
we cannot use the master branch. If it passes all tests, it still does not mean that it will pass all tests in the latest Pharo too (it can fail on release or dependency tests)

**Comment by jecisc** [comment]
@pavel-krivanek But, would it be possible now (or soon) to depend on Metacello via tags as with Iceberg?

**Comment by dalehenrich** [comment]
@pavel-krivanek this is a ludicrous statement: 

> we cannot use the master branch. If it passes all tests, it still does not mean that it will pass all tests in the latest Pharo too (it can fail on release or dependency tests)

Metacello runs integration tests via travis-ci before anything is merged into the master branch ... Pharo runs integration tests after every build if the tests pass, you ship the release. If the tests fail, you fix the resulting issues. If it turns out that Pharo has untested dependencies on Metacello then I think that that is a problem in Pharo and not Metacello ... Pharo is free to extend the tests in Metacello to provide coverage for any dependencies that you might have on Metacello. I am also open to discussing changes to Metacello that would make it possible for you guys to use Metacello without hacking away on Metacello.

At the moment Pharo 7.0 is not being tested by Metacello on Travis, because Pharo-7.0 could not load Metacello correctly from the master branch ... which is not a good thing --- you guys are doing something wrong if you can't load Metacello. Now perhaps that problem has been fixed, but it is a major issue and it is a problem with Pharo not Metacello ...

I've been maintaining Metacello for almost a decade and to my knowledge I have never broken anyone's builds by making a mistake by releasing junk. 

There **was**, however, a 2 year run where Pharo was not using the latest Metacello code --- again you guys messed up by **not** using the latest Metacello master branch --- I was regularly telling people on the mailing list  who were running into "metacello bugs" that all they needed to do was to load the latest version of Metacello from github where the bug had been fixed for years!

So if you tell me that Pharo cannot use the Metacello master branch because you guys don't have your act together then I can believe that.

**Comment by dalehenrich** [comment]
At the end of the day, don't you agree that this is "simply" a process issue? 

If you guys can't easily handle one of the most fundamental operations: integrating a "third party" project into your build process (without copying the entire source tree) then how do you expect anyone else to do so ...

I don't think it should be this hard and I don't quite understand what the problem could be ...

Right now I am using Metacello to bootstrap code into a GemStone base image and at the end of the process I end with the standard Metacello release being present --- but there is a bit of monkey busness ... bootstrapping does present problems, so if you are using Metacello to bootstrap the Pharo image then I can understand the difficulty, but even doing this it should be possible to present the standard Metacello release to the end users and it is presenting the standard Metacello release to end users that I think is important ...

So I am mystified as to what the difficulty must be...

I am willing to get technical with you guys and share more details about what I do for GemStone-- but I don't think it is really acceptable to "just say no"

**Comment by pavel-krivanek** [comment]
Yes, it would be possible to use tags on the master branch. On the other hand, let's suppose that we will make a code freeze and then only the bugfixes should be accepted. Then you may need to integrate some bugfixes but the master branch can add new features. 

In fact, this is mostly theoretical argument because our code freeze is not so strict as it can be seen on examples of Epica and Iceberg, but in future, we should follow our own rules :-) 

The current process is not set well mostly because we are waiting on subdirectories support in Iceberg and the fact that Iceberg is managed as an external project a side-effect, not planed goal.

Ad dependencies, I meant that Metacello itself can break some dependency or release tests in Pharo because they may become more strict.

**Comment by dalehenrich** [comment]
thanks @pavel-krivanek tagging releases would be easy enough to do ... let me know the process that I should go through to notify you of a new tagged release and then I'll start following that process ...

**Comment by dalehenrich** [comment]
@pavel-krivanek to the extent that it is possible it would make a lot sense to move (or copy) the stricter tests into the Metacello code base ... I would be happy to have you do this --- if there are stricter tests in pharo, then the earlier that Metacello fails these tests ... I would not merge a PR request from  another developer unless they met the stricter requirements and if they were actually using travis to do their development they would not submit a pr without making sure that all tests are passing ...

Hopefully Metacello will be able to start running travis tests against pharo7.0 soon ...

**Comment by astares** [comment]
Hi @dalehenrich and @pavel-krivanek thanks for caring. 

@dalehenrich 
Note that meanwhile we have a package "release tests" with some quality standard
defined in unit tests to shape and enforce a proper Pharo release (proper categorization, no unused temps, the tearDowns issue and more, ...). There will be more in the near future.
The idea is not only to clean the code but have tests making sure we keep the quality level and
do not have to fix the same stuff over and over again.

As a minimum Metacello should (beside own tests) have them green too - otherwise we will 
have trouble to integrate (tagged or not). 

It would also be good if the Metacello classes could be documented.

**Comment by dalehenrich** [comment]
@astares these are exactly the type of tests I would want to have moved/copied to the Metacello project test suite ... I don't mind meeting Pharo's higher standards and enforcing those standards on all platforms ... 

With regards to class comments I would like that too:) As it stands there seem to be 140 classes in a GemStone image (not including tests) and if the comment-based tests were moved into Metacello  I would undertake the task of writing comments for the Metacello classes (on a separate branch with the tests since it will take me time) ... it would really help to have reviewers to review the comments or better yet tell me from an outsiders perspective what is important to document especially in some of the more obscure classes --- I can write meaningless comments with the best of them, which is why I don't write comments at the outset, but if there are meaningful questions that can be answered by a comment, then I am willing to supply the answers ...

**Comment by astares** [comment]
I wonder why it is a usual practice to "simply say what a class is about" in NEARLY ALL widespread mainstream languages while in Smalltalk we simply are not able to do our homework. Or why we have to wait until a question needs to pop up before we move and start commenting a class. Sorry - this is beyond my horizon and people laugh each time one talks about "sophisticated" tools and afterwards opens an image with lots of exclamation marks because people are not able to write a single line about the reasoning behind creating a class.

If one requires more or less 5 minutes to implement a class why not take 10 seconds to write down "why" the class is created or for what purpose it is useful. One does not have to explain all ivars or behavior in detail - a simple "WHY IS THIS CLASS HERE" kind of style would already help and move us all forward. Such a simple comment is already helpful and very stable - because the original intention for a class often stay the same even when ivars are added or removed or methods, API and signatures change.

Even a simple "this class is used for X and Y" would tell us more than just having an uncommented class with just a name. And we always here the same arguments for non-commented classes: no time to do it in a perfect way. (which often means it will never be done)

Hey - a comment must not be perfect - it just needs to be added. I'm annoyed to fix each Pharo release by adding class comments or play games like "class comment of the day" on the mailinglist to improve the situation. And I hate it when afterwards again packages are loaded in the same uncommented way leaving the image again in a chaotic way for the next iteration. 

So we need to do it: clean up but also comment and enforce with a test that we can than keep our standard. 

For any uncommented class we have 10 newbies running around asking questions keeping us all away from important things and everytime an uncommented class is loaded a sweet colorful unicorn dies. 

For sure I can do it as well ... but I guess it easier for you to write 140 simple comments on your own than reviewing + correcting 140 comments that I did not reflecting the idea/intention why a class is there.

So please comment and help to improve the situation - step by step, a few each day, start with a simple line for each class and then 140 is not a big number. Believe me you will feel like a hero afterwards !!!

If you do not or can not then I will for sure do it. But do not say I did not warn you! Even more unicorns will die then because my comments might not be good as yours ;)

**Comment by dalehenrich** [comment]
There are a couple of reasons that I do not like comments (these are not **excuses** ... I agree that good documentation is needed **BUT** :) ... 
1. As a developer I really hate to read comments ... I have hit enough `incorrect comments` over the years that I no longer "waste my time" reading comments (note my caveat about **excuses**) ... I simply read the code and over the years I have found that reading code is a reliable way to understand what is going --- whether or not good comments are present ...
2. I have a *personality disorder* where I find myself incapable of writing a good comment ... I am **very** literal minded - to an extreme ... whenever I try to write comments or documentation I end up saying what the code already says only I don't do quite as good a job as the code and it seems a completely redundant excercise ... so for  me it is a painful process to either write something that is an imperfect description of the actual code or I write something that even I don't understand or need ...

As an example I haven't been able to actually read the wonderful documentation that Stef and Mariano put together on Metacello, because I can't get past the first page without being uncomfortable with the imperfections in the descriptions (not that Stef and Mariano are bad wirters -- it is because I understand the Metacello code in a way that I cannot verbalize and I cannot generalize). Intellectually I understand that these *imperfections* are part of good writing (I think), but for me it is very difficult to describe complicated processes without writing complicated descriptions ... 

Some ome folks have the gift for writing understandable descriptions (like the Metacello documentation - good work Stef and Mariano), but I have the opposite of that gift ...

So don't worry about me wanting to correcting your descriptions ... perhaps you will be my  *documentation muse* and inspire me to revise your work and even learn how to write my own good comments. 

We can only hope, though:)

**Comment by astares** [comment]
https://github.com/Metacello/metacello/pull/479 was merged.

**Comment by dalehenrich** [comment]
@astares ... and it appears that our opinions differ and I can live with that ... 

But you seem to have ignored the bits where I offered to write comments in order to get the tighter Pharo reguirment tests ported to the main Metacello repository... so your crack about lazy is not called for...

**Pull request merged**
