### PR TITLE
21166-Make-Glamour-Example-Browser-searchable

### PR DESCRIPTION
**Pull request by JurajKubelka**
fixes case 21166
https://pharo.manuscript.com/f/cases/21166/Make-Glamour-Example-Browser-searchable

### CODE REVIEW

**Comment by Ducasse** [comment]
I do not understand anything to our infrastructure anymore. I will not integrate fix anymore. 
Each time I do it something break. I do not understand why this fix conflict.

**Comment by MarcusDenker** [comment]
The problem is that the CI is in a bad state. (I think in addition, now the mac slave is down). It does not conflict, it just can not build it.

We need to fix this, but for very very simple things that can be tested by hand I decide that I integrate them nevertheless... maybe not a good idea?

**Comment by Ducasse** [comment]
I understand the problem is that last time I did that I broke the build because the configuration of IDE had to be changed :)
So Pavel told me that he will fix it but I do not like to break things.

**Comment by Ducasse** [comment]
I wonder if we cannot have our own slaves?

**Comment by astares** [comment]
So far (despite the trouble with CI) it seems to work mostly, we are still green:
https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/development/

At least I have a daily look on this CI build to double check.

I understand that one does not want to get blamed for breaking the CI - but even a green build is not a guarantee for beeing error-free.

**Pull request merged**
