### PR TITLE
20513-Rename-ComposableModel-to-ComposablePresenter

### PR DESCRIPTION
**Pull request by pavel-krivanek**
https://pharo.fogbugz.com/f/cases/20513/Rename-ComposableModel-to-ComposablePresenter

- rename ComposableModel to ComposablePresenter and do the similar operation with the subclasses
- create deprecated subclasses with the old name because of the old code compatibility
- modify class comments where possible
- do not touch other than Spec packages

### CODE REVIEW

**Comment by astares** [comment]
I guess 
 - lots of code need to be rewritten
 - lots of external packages need to be adopted 
 - as well as (Spec) books 
because of this PR ...

**Comment by pavel-krivanek** [comment]
In Spec book:
Considering the construction and orchestration of the different widgets in
a user interface, Spec is inspired by the Model-View-Presenter pattern. The
model that is defined in Spec corresponds to a presenter in the MVP triad.
Note that because of this, future versions of Spec may rename the ComposableModel
into ComposablePresenter for naming consistency.

Yes, a lot of code and documentation must be adopted but we have only two options - do it as soon as possible or never. That this change must be done was determined more than year ago by Stef, Peter and others from the RMOD team. Spec needs a lot of changes and this one is the most visible and painful. 

All changes will be done as deprecations and currently it does not disturb users by any exception or automatic code rewriting.

**Comment by pavel-krivanek** [comment]
current test failures seem to be random

**Comment by Ducasse** [comment]
For the book I will just do a new version. I like the change because I made a mistake not to be smart enough to use Presenter in the first day. 
I will check it and I would like to introduce more enhancements (on: + menu declaration).

**Pull request merged**
