### PR TITLE
20321 add build number to system version

### PR DESCRIPTION
**Pull request by guillep**
SystemVersion right now does not store the build number and it does not print the hash of the commit to reproduce the system.

https://pharo.fogbugz.com/f/cases/20321/Add-build-number-to-SystemVersion

### CODE REVIEW

**Comment by jecisc** [comment]
This will also close this issue: https://pharo.fogbugz.com/f/cases/20293/SystemReporter-is-not-useful-in-Pharo-7

**Comment by astares** [comment]
Very good - works!

**Comment by pavel-krivanek** [comment]
printVersion (command-line handler) should use the new information

**Comment by guillep** [comment]
I added it in a new commit

**Comment by pavel-krivanek** [comment]
it now prints the version with quotes: 
```[version] 'Pharo7.0' 'Pharo-7.0-alpha.build.5.sha.58d59bb3d176d9a5ba3c3192e5b6c8```
is that expected?

**Pull request merged**
