### PR TITLE
New working directory implementation

### PR DESCRIPTION
**Pull request by rajula96reddy**
Created new methods to get the current working directory. Added a few unit tests. Patched an existing method.

### CODE REVIEW

**Comment by estebanlm** [comment]
sorry, which issue is this addressing?

**Comment by guillep** [comment]
Hi @rajula96reddy, you should follow the example of the other pull requests:

https://github.com/pharo-project/pharo/pulls

- open an issue in fogbugz if there is not one
- create in your repository a branch named by the issue. That is "IssueNbr-IssueName". Like other PRs
- Then, you have to make your pull request to the development branch, and not to master

@estebanlm am I missing something?

**Comment by estebanlm** [comment]
no, that's correct @guillep :)

**Comment by estebanlm** [comment]
in fact I don't care about the origin name, but the PR needs to have the issue number - issue explanation on name (this is done automatically by PR tool on iceberg)

**Comment by rajula96reddy** [comment]
@estebanlm Sorry my fault. I didn`t know the guidelines. I will correct it and submit a new request. 
@guillep Thanks for the heads up. I will follow the same.

**Pull request closed without merging**
