### PR TITLE
20400 Properly categorize #= methods in comparing and add a release test th…

### PR DESCRIPTION
**Pull request by astares**
Properly categorize #= methods in comparing aand add a release test that checks this

### CODE REVIEW

**Comment by astares** [comment]
https://pharo.fogbugz.com/f/cases/20400/All-methods-should-be-properly-categorized

**Comment by jecisc** [comment]
I think the tests of this PR needs to be relaunch

**Comment by astares** [comment]
How?

**Comment by jecisc** [comment]
I think only people with the rights on the pharo jenkins can.

**Comment by MarcusDenker** [comment]
only networking related tests are failing, nothing related to this change

**Pull request merged**
