### PR TITLE
05723-Default-Working-Directory

### PR DESCRIPTION
**Pull request by rajula96reddy**
This is a new pull request made as a part of my Google Summer of Code 2017 project, the last one had unnecessary commits.

### CODE REVIEW

**Comment by guillep** [comment]
run tests

**Comment by guillep** [comment]
run tests

**Comment by jecisc** [comment]
In order to not flood too much the history maybe we could squash all the change in protocols?

**Comment by guillep** [comment]
I'm not a big fan of squashing or messing with the history for "readability"... I know this is an edge case, but It's also not a so complicated stream of changes. Does the effort really add a big value?

**Comment by jecisc** [comment]
I was taught to keep a clean git history. It usually helps me when I need to do changelog, but maybe it is useless for projects as big as Pharo because history will be hard to read anyway.

**Comment by guillep** [comment]
I prefer to do small commits in general, so reverting them is easy. It is harder to revert a small part of a squashed commit...

I revert changes more often than I "read the logs" of unknown changes.

In any case, this does not apply to these particular commits. I just made the change in many commits because it was faster. If somebody wants to squash those 10 commits, I'm not particularly against.

**Pull request merged**
